// Vokabeldaten - 922 Wörter in 30 Kategorien
const vocabulary = {
  "Begrüßungen & Höflichkeit": {
    icon: "👋",
    words: [
      { ar: "مَرْحَباً", en: "hello" },
      { ar: "صَباح اَلْخَيْر", en: "good morning" },
      { ar: "صَباح اَلْنّور", en: "good morning to you" },
      { ar: "مَساء اَلْخَيْر", en: "good evening" },
      { ar: "مَساء اَلْنّور", en: "good evening to you too" },
      { ar: "أَهْلاً", en: "hello" },
      { ar: "شُكْراً", en: "thank you" },
      { ar: "عَفْواً", en: "excuse me, you're welcome" },
      { ar: "مَعَ ٱلْسَّلامة", en: "goodbye" },
      { ar: "إِلى ٱلْلِّقاء", en: "until next time" },
      { ar: "يَوْم سَعيد", en: "have a nice day" },
      { ar: "اَلْسَّلامُ عَلَيْكُم", en: "peace be upon you" },
      { ar: "وَعَلَيْكُمُ ٱلْسَّلام", en: "and upon you be peace" },
      { ar: "إِنْ شاءَ ٱلله", en: "God willing" },
      { ar: "اَلْحَمْدُ لِله", en: "praise be to God" },
      { ar: "يَلّا", en: "alright" },
      { ar: "تَمام", en: "OK" },
      { ar: "تَشَرَّفْنا", en: "pleasure to meet you" },
      { ar: "كَيْفَك", en: "how are you (m)" },
      { ar: "كَيْفِك", en: "how are you (f)" },
      { ar: "بِخَيْر", en: "well, OK" },
      { ar: "تَفَضَّل", en: "go ahead, come in, here you go" },
      { ar: "تَفَضَّلي", en: "here you go (f)" },
      { ar: "تَفَضَّلوا", en: "here you go (pl)" },
      { ar: "مِن فَضْلِك", en: "please (f)" },
      { ar: "مِن فَضْلَك", en: "please (m)" },
      { ar: "أَلو", en: "hello (phone)" },
      { ar: "آسِف", en: "sorry" },
      { ar: "تَعالَ", en: "come (m)" },
      { ar: "تَعالي", en: "come (f)" },
      { ar: "تَعالوا", en: "come (pl)" },
      { ar: "اَلله يُسَلِّمَك", en: "thank you" },
      { ar: "اَلله يُسَلِّمِك", en: "thank you (f)" },
      { ar: "سَلامتَك", en: "get better (m)" },
      { ar: "سَلامتِك", en: "get better (f)" },
    ],
  },
  "Familie & Beziehungen": {
    icon: "👨‍👩‍👧‍👦",
    words: [
      { ar: "أَب", en: "father" },
      { ar: "أُمّ", en: "mother" },
      { ar: "أَخ", en: "brother" },
      { ar: "أُخْت", en: "sister" },
      { ar: "اِبْن", en: "son" },
      { ar: "بِنْت", en: "daughter, a girl" },
      { ar: "جَدّ", en: "grandfather" },
      { ar: "جَدّة", en: "grandmother" },
      { ar: "عَمّ", en: "uncle" },
      { ar: "خالة", en: "aunt" },
      { ar: "بِنْت عَمّ", en: "cousin" },
      { ar: "زَوْج", en: "husband" },
      { ar: "زَوْجة", en: "wife" },
      { ar: "عائِلة", en: "family" },
      { ar: "وَلَد", en: "boy, child" },
      { ar: "رَجُل", en: "man" },
      { ar: "اِمْرَأة", en: "woman" },
      { ar: "صَديق", en: "friend (m)" },
      { ar: "صَديقة", en: "friend (f)" },
      { ar: "جار", en: "neighbor (m)" },
      { ar: "جارة", en: "neighbor (f)" },
      { ar: "زَميل", en: "colleague, classmate" },
      { ar: "أَبي", en: "my father" },
      { ar: "أُمّي", en: "my mother" },
      { ar: "أَخي", en: "my brother" },
      { ar: "أُخْتي", en: "my sister" },
      { ar: "اِبْني", en: "my son" },
      { ar: "بِنْتي", en: "my daughter" },
      { ar: "جَدّي", en: "my grandfather" },
      { ar: "جَدَّتي", en: "my grandmother" },
      { ar: "زَوْجي", en: "my husband" },
      { ar: "زَوْجَتي", en: "my wife" },
      { ar: "أَخو", en: "brother of" },
      { ar: "مُتَزَوِّج", en: "married" },
      { ar: "مُطَلَّق", en: "divorced" },
      { ar: "قَريب", en: "relative, close" },
      { ar: "أَقارِب", en: "relatives" },
      { ar: "أَصْدِقاء", en: "friends" },
      { ar: "ناس", en: "people, folks" },
    ],
  },
  "Kleidung & Accessoires": {
    icon: "👔",
    words: [
      { ar: "فُسْتان", en: "dress" },
      { ar: "فَساتين", en: "dresses" },
      { ar: "بَدْلة", en: "a suit" },
      { ar: "بَدَلات", en: "suits" },
      { ar: "قَميص", en: "shirt" },
      { ar: "قُمْصان", en: "shirts" },
      { ar: "مَعاطِف", en: "coats" },
      { ar: "مِعْطَف", en: "coat" },
      { ar: "قُفّازات", en: "gloves" },
      { ar: "مَلابِس", en: "clothes" },
      { ar: "جَوارِب", en: "socks" },
      { ar: "نَظّارات", en: "glasses" },
      { ar: "حِذاء", en: "shoes" },
      { ar: "بِنْطال", en: "pants" },
      { ar: "حِزام", en: "belt" },
      { ar: "سُتْرة", en: "jacket" },
      { ar: "بَلوزة", en: "blouse" },
      { ar: "تَنّورة", en: "skirt" },
      { ar: "تي شيرْت", en: "t-shirt" },
      { ar: "وِشاح", en: "scarf" },
      { ar: "قُبَّعة", en: "hat" },
      { ar: "جاكيت", en: "jacket" },
      { ar: "صوف", en: "wool" },
      { ar: "كُمّ", en: "sleeves" },
      { ar: "كُم", en: "sleeves" },
      { ar: "لابِس", en: "wearing (m)" },
      { ar: "لابِسة", en: "wearing (f)" },
    ],
  },
  Farben: {
    icon: "🎨",
    words: [
      { ar: "لَوْن", en: "color" },
      { ar: "وَرْدِيّ", en: "pink" },
      { ar: "أَبْيَض", en: "white (m)" },
      { ar: "بَيْضاء", en: "white (f)" },
      { ar: "أَزْرَق", en: "blue (m)" },
      { ar: "زَرْقاء", en: "blue (f)" },
      { ar: "بُنِّيّ", en: "brown (m)" },
      { ar: "بُنِّيّة", en: "brown (f)" },
    ],
  },
  "Essen & Trinken": {
    icon: "🍽️",
    words: [
      { ar: "فُطور", en: "breakfast" },
      { ar: "غَداء", en: "lunch" },
      { ar: "عَشاء", en: "dinner" },
      { ar: "أَكْل", en: "food" },
      { ar: "خُبْز", en: "bread" },
      { ar: "خُبْزاً", en: "bread (acc)" },
      { ar: "رُزّ", en: "rice" },
      { ar: "اَلْرُّزّ", en: "rice" },
      { ar: "سَلَطة", en: "salad" },
      { ar: "شورْبة", en: "soup" },
      { ar: "حُمُّص", en: "hummus" },
      { ar: "حُمُّصاً", en: "hummus (acc)" },
      { ar: "فَلافِل", en: "falafel" },
      { ar: "كِبّة", en: "kibbeh" },
      { ar: "كَباب", en: "kebab" },
      { ar: "كَباباً", en: "kebab (acc)" },
      { ar: "تَبّولة", en: "tabbouleh" },
      { ar: "مُقَبِّلات", en: "appetizers" },
      { ar: "طَبَق", en: "dish" },
      { ar: "حَلْوى", en: "dessert" },
      { ar: "كَعْك", en: "cake" },
      { ar: "سَمَك", en: "fish" },
      { ar: "دَجاج", en: "chicken" },
      { ar: "بَطاطا", en: "potatoes" },
      { ar: "جَزَر", en: "carrots" },
      { ar: "بَنَدورة", en: "tomatoes" },
      { ar: "كوسا", en: "squash" },
      { ar: "بامْيا", en: "okra" },
      { ar: "بَصَل", en: "onions" },
      { ar: "خُضْراوات", en: "vegetables" },
      { ar: "فاكِهة", en: "fruit" },
      { ar: "موزة", en: "banana" },
      { ar: "توت", en: "strawberries, berry" },
      { ar: "جُبن", en: "cheese" },
      { ar: "اَلْثّوم", en: "the garlic" },
      { ar: "قَهْوة", en: "coffee" },
      { ar: "شاي", en: "tea" },
      { ar: "شاياً", en: "tea (acc)" },
      { ar: "عَصير", en: "juice" },
      { ar: "عَصيراً", en: "juice (acc)" },
      { ar: "ماء", en: "water" },
      { ar: "حَليب", en: "milk" },
      { ar: "مَشْروب", en: "drink" },
      { ar: "صِحِّيّ", en: "healthy" },
      { ar: "طازِج", en: "fresh" },
      { ar: "حارّ", en: "spicy, hot" },
      { ar: "بارِد", en: "cold" },
      { ar: "بارِداً", en: "cold (acc)" },
      { ar: "ساخِناً", en: "warm (acc)" },
      { ar: "طَيِّب", en: "good, kind" },
      { ar: "طَيِّباً", en: "good (acc)" },
    ],
  },
  "Körper & Gesundheit": {
    icon: "🏥",
    words: [
      { ar: "عَيْن", en: "eye" },
      { ar: "يَد", en: "hand" },
      { ar: "فَم", en: "mouth" },
      { ar: "أَسْنان", en: "teeth" },
      { ar: "شَعْر", en: "hair" },
      { ar: "طَبيب", en: "doctor" },
      { ar: "دُكْتور", en: "doctor" },
      { ar: "دُكْتورة", en: "doctor (f)" },
      { ar: "مَريض", en: "sick" },
      { ar: "صُداع", en: "headache" },
      { ar: "أَلَم", en: "pain" },
      { ar: "حَرارة", en: "fever" },
      { ar: "قَوِيّ", en: "strong" },
      { ar: "ما بِكَ", en: "what is wrong (m)" },
      { ar: "ما بِكِ", en: "what is wrong (f)" },
      { ar: "أَشْعُر", en: "I feel" },
      { ar: "تَرْتاحي", en: "you rest (f)" },
      { ar: "تَرْتاحوا", en: "you rest (pl)" },
      { ar: "يَرْتاحوا", en: "they rest" },
      { ar: "أَرْتاح", en: "I rest, I relax" },
      { ar: "اِسْتِراحة", en: "break" },
      { ar: "صابون", en: "soap" },
      { ar: "شامْبو", en: "shampoo" },
      { ar: "مَعْجون أَسْنان", en: "toothpaste" },
      { ar: "فُرْشاة أَسْنان", en: "toothbrush" },
      { ar: "رائِحة", en: "smell" },
      { ar: "فُوَط", en: "towels" },
    ],
  },
  "Berufe & Arbeit": {
    icon: "💼",
    words: [
      { ar: "مِهْنة", en: "a profession" },
      { ar: "عَمَل", en: "work, job" },
      { ar: "مُدير", en: "manager, director" },
      { ar: "مُوَظَّف", en: "employee" },
      { ar: "مُهَنْدِس", en: "engineer (m)" },
      { ar: "مُهَنْدِسة", en: "engineer (f)" },
      { ar: "مُعَلِّم", en: "teacher (m)" },
      { ar: "مُعَلِّمة", en: "teacher (f)" },
      { ar: "أُسْتاذ", en: "professor (m)" },
      { ar: "أُسْتاذة", en: "professor (f)" },
      { ar: "مُحامي", en: "lawyer" },
      { ar: "مُحاسِب", en: "accountant" },
      { ar: "مُتَرْجِم", en: "translator (m)" },
      { ar: "مُتَرْجِمة", en: "translator (f)" },
      { ar: "مُصَوِّر", en: "photographer" },
      { ar: "باحِث", en: "researcher" },
      { ar: "طالِب", en: "student" },
      { ar: "بائِع", en: "vendor" },
      { ar: "جُنْدِيّ", en: "soldier" },
      { ar: "قاضي", en: "judge" },
      { ar: "رَبّ بَيْت", en: "homemaker (m)" },
      { ar: "رَبّة بَيْت", en: "homemaker (f)" },
      { ar: "مَصْنَع", en: "factory" },
      { ar: "شَرِكة", en: "company" },
      { ar: "مَكْتَب", en: "office" },
      { ar: "أَعْمَل", en: "I work" },
      { ar: "تَعْمَلين", en: "you work (f)" },
      { ar: "تَعْمَل", en: "you/she works" },
      { ar: "مَشْغول", en: "busy" },
      { ar: "مُتَفَرِّغ", en: "free" },
    ],
  },
  "Haus & Wohnung": {
    icon: "🏠",
    words: [
      { ar: "بَيْت", en: "house, home" },
      { ar: "بيت", en: "house, home" },
      { ar: "شَقّة", en: "apartment" },
      { ar: "غُرْفة", en: "room" },
      { ar: "غُرْفة نَوْم", en: "bedroom" },
      { ar: "مَطْبَخ", en: "kitchen" },
      { ar: "حَمّام", en: "bathroom" },
      { ar: "صالون", en: "living room" },
      { ar: "شُرْفة", en: "balcony" },
      { ar: "مَمَرّ", en: "hallway" },
      { ar: "كَراج", en: "garage" },
      { ar: "حَديقة", en: "garden" },
      { ar: "باب", en: "door" },
      { ar: "شُبّاك", en: "window" },
      { ar: "حائِط", en: "wall" },
      { ar: "سَرير", en: "bed" },
      { ar: "كُرْسي", en: "chair" },
      { ar: "طاوِلة", en: "table" },
      { ar: "تِلْفاز", en: "television" },
      { ar: "مُلاءات", en: "sheets" },
      { ar: "إيجار", en: "rent" },
      { ar: "بِناية", en: "building" },
      { ar: "في ٱلْطّابِق اَلْأَوَّل", en: "on the first floor" },
      { ar: "في ٱلْطّابِق اَلْثّاني", en: "the second floor" },
      { ar: "شارِع", en: "street" },
      { ar: "ضَوْء", en: "light" },
      { ar: "صَوْت", en: "noise" },
      { ar: "ضَجّة", en: "noise" },
      { ar: "مُشْكِلة", en: "problem" },
      { ar: "مَكْسور", en: "broken" },
      { ar: "مُعَطَّل", en: "out of order" },
      { ar: "نَظيف", en: "clean" },
      { ar: "وَسِخ", en: "dirty" },
      { ar: "واسِع", en: "spacious (m)" },
      { ar: "واسِعة", en: "spacious (f)" },
      { ar: "مَسْبَح", en: "swimming pool" },
      { ar: "صالة رِياضِيّة", en: "gym" },
      { ar: "فُنْدُق", en: "hotel" },
      { ar: "حَجْز", en: "reservation" },
      { ar: "مَمْنوع", en: "forbidden" },
    ],
  },
  "Länder & Städte": {
    icon: "🌍",
    words: [
      { ar: "بَلَد", en: "country" },
      { ar: "بِلاد", en: "countries" },
      { ar: "مَدينة", en: "city" },
      { ar: "عاصِمة", en: "capital" },
      { ar: "قَرْية", en: "village" },
      { ar: "وِلاية", en: "state" },
      { ar: "جَزيرة", en: "island" },
      { ar: "مِصْر", en: "Egypt" },
      { ar: "اَلْقاهِرة", en: "Cairo" },
      { ar: "سوريا", en: "Syria" },
      { ar: "دِمَشْق", en: "Damascus" },
      { ar: "لُبْنان", en: "Lebanon" },
      { ar: "بَيْروت", en: "Beirut" },
      { ar: "اَلْعِراق", en: "Iraq" },
      { ar: "بَغْداد", en: "Baghdad" },
      { ar: "فِلَسْطين", en: "Palestine" },
      { ar: "اَلْأُرْدُن", en: "Jordan" },
      { ar: "اَلْيَمَن", en: "Yemen" },
      { ar: "اَلْسّودان", en: "Sudan" },
      { ar: "اَلْخَرطوم", en: "Khartoum" },
      { ar: "عُمان", en: "Oman" },
      { ar: "تونِس", en: "Tunisia" },
      { ar: "مالْطا", en: "Malta" },
      { ar: "أوروبّا", en: "Europe" },
      { ar: "آسْيا", en: "Asia" },
      { ar: "أَمريكا", en: "America" },
      { ar: "فَرَنْسا", en: "France" },
      { ar: "باريس", en: "Paris" },
      { ar: "أَلْمانْيا", en: "Germany" },
      { ar: "بَرْلين", en: "Berlin" },
      { ar: "إِنْجِلْتِرا", en: "England" },
      { ar: "إِسْكُتْلَنْدا", en: "Scotland" },
      { ar: "هولَنْدا", en: "Holland" },
      { ar: "أَمْسْتِرْدام", en: "Amsterdam" },
      { ar: "كَنَدا", en: "Canada" },
      { ar: "أُسْتُرالْيا", en: "Australia" },
      { ar: "إيطالْيا", en: "Italy" },
      { ar: "اَلْصّين", en: "China" },
      { ar: "نْيويورْك", en: "New York" },
      { ar: "كوبا", en: "Cuba" },
      { ar: "بيرو", en: "Peru" },
      { ar: "كوريا", en: "Korea" },
      { ar: "ريجا", en: "Riga" },
      { ar: "باكو", en: "Baku" },
      { ar: "داكار", en: "Dakar" },
      { ar: "جوبا", en: "Juba" },
      { ar: "اَلْإِسْكَنْدَرِيّة", en: "Alexandria" },
      { ar: "وِلاية جورْجْيا", en: "the state of Georgia" },
      { ar: "مَدينة لوس أَنْجِلِس", en: "the city of Los Angeles" },
      { ar: "وِلاية كاليفورْنْيا", en: "the state of California" },
      { ar: "مَدينة سافانا", en: "the city of Savannah" },
      {
        ar: "اَلْبَحْر اَلْأَبْيَض اَلْمُتَوَسِّط",
        en: "the Mediterranean Sea",
      },
    ],
  },
  Nationalitäten: {
    icon: "🏳️",
    words: [
      { ar: "عَرَبِيّ", en: "Arab (m)" },
      { ar: "عَرَبِيّة", en: "Arab (f), Arabic" },
      { ar: "مِصْرِيّ", en: "Egyptian (m)" },
      { ar: "سورِيّ", en: "Syrian (m)" },
      { ar: "سورِيّة", en: "Syrian (f)" },
      { ar: "لُبنانِيّ", en: "Lebanese (m)" },
      { ar: "لُبْنانِيّة", en: "Lebanese (f)" },
      { ar: "أُرْدُنِيّ", en: "Jordanian (m)" },
      { ar: "أُرْدُنِيّة", en: "Jordanian (f)" },
      { ar: "فِلَسْطينِيّة", en: "Palestinian (f)" },
      { ar: "عُمانِيّ", en: "Omani" },
      { ar: "تونِسِيّ", en: "Tunisian (m)" },
      { ar: "تونِسِيّة", en: "Tunisian (f)" },
      { ar: "مَغْرِبِيّ", en: "Moroccan (m)" },
      { ar: "مَغْرِبِيّة", en: "Moroccan (f)" },
      { ar: "أَمريكِيّ", en: "American (m)" },
      { ar: "أَمْريكِيّة", en: "American (f)" },
      { ar: "فَرَنْسِيّ", en: "French (m)" },
      { ar: "فَرَنْسِيّة", en: "French (f)" },
      { ar: "إِنْجِليزِيّ", en: "English" },
      { ar: "إِسْكُتْلَنْدِيّ", en: "Scottish" },
      { ar: "هولَنْدِيّ", en: "Dutch" },
      { ar: "كَنَدِيّ", en: "Canadian" },
    ],
  },
  "Zeit & Kalender": {
    icon: "🕐",
    words: [
      { ar: "وَقْت", en: "time" },
      { ar: "ساعة", en: "time, watch, one hour" },
      { ar: "يَوْم", en: "day" },
      { ar: "أُسْبوع", en: "week" },
      { ar: "شَهْر", en: "month" },
      { ar: "سَنة", en: "year" },
      { ar: "صَباح", en: "morning" },
      { ar: "مَساء", en: "evening" },
      { ar: "صَباحاً", en: "in the morning" },
      { ar: "مَساءً", en: "in the evening" },
      { ar: "بِالْلَّيْل", en: "at night" },
      { ar: "بَعْد اَلْظُّهْر", en: "in the afternoon" },
      { ar: "اَلْيَوْم", en: "today" },
      { ar: "أَمْس", en: "yesterday" },
      { ar: "قَبْل", en: "before" },
      { ar: "بَعْد", en: "after" },
      { ar: "مُنْذُ", en: "for, since, ago" },
      { ar: "لاحِقاً", en: "later" },
      { ar: "قَريباً", en: "soon" },
      { ar: "دائِماً", en: "always" },
      { ar: "أَحْياناً", en: "sometimes" },
      { ar: "عادةً", en: "usually" },
      { ar: "مُبَكِّراً", en: "early" },
      { ar: "في ساعة مُتَأَخِّرة", en: "late" },
      { ar: "لَحْظة", en: "one moment" },
      { ar: "مَرّة", en: "time, once" },
      { ar: "مَرّة أُخْرى", en: "again" },
      { ar: "مَوْعِد", en: "appointment" },
      { ar: "نِهاية اَلْأُسْبوع", en: "weekend" },
      { ar: "اَلْآن", en: "now" },
      { ar: "اَلآن", en: "now" },
      { ar: "رَمَضان", en: "Ramadan" },
    ],
  },
  Uhrzeiten: {
    icon: "⏰",
    words: [
      { ar: "كَم اَلْسّاعة", en: "what time is it" },
      { ar: "في أَيّة ساعة", en: "at what time" },
      { ar: "نُصْف", en: "half" },
      { ar: "اَلْسّاعة ٱلْواحِدة", en: "one o'clock" },
      { ar: "اَلْسّاعة ٱلْثّانْية", en: "two o'clock" },
      { ar: "اَلْسّاعة ٱلْثّالِثة", en: "three o'clock" },
      { ar: "اَلْسّاعة ٱلْرّابِعة", en: "four o'clock" },
      { ar: "اَلْسّاعة ٱلْخامِسة", en: "five o'clock" },
      { ar: "اَلْسّاعة ٱلْسّادِسة", en: "six o'clock" },
      { ar: "اَلْسّاعة ٱلْسّابِعة", en: "seven o'clock" },
      { ar: "اَلْسّاعة ٱلْثّامِنة", en: "eight o'clock" },
      { ar: "اَلْسّاعة ٱلْتّاسِعة", en: "nine o'clock" },
      { ar: "اَلْسّاعة ٱلْعاشِرة", en: "ten o'clock" },
      { ar: "اَلْسّاعة ٱلْحادْية عَشْرة", en: "eleven o'clock" },
      { ar: "اَلْسّاعة ٱلْثّانْية عَشْرة", en: "twelve o'clock" },
    ],
  },
  Zahlen: {
    icon: "🔢",
    words: [
      { ar: "٠", en: "0" },
      { ar: "١", en: "1" },
      { ar: "٢", en: "2" },
      { ar: "٣", en: "3" },
      { ar: "٤", en: "4" },
      { ar: "٥", en: "5" },
      { ar: "٦", en: "6" },
      { ar: "٧", en: "7" },
      { ar: "٨", en: "8" },
      { ar: "٩", en: "9" },
      { ar: "١٠", en: "10" },
      { ar: "واحِد", en: "one" },
      { ar: "كيلو", en: "kilo" },
      { ar: "دينار", en: "dinar" },
      { ar: "دَنانير", en: "dinars" },
      { ar: "بِكَم", en: "how much" },
      { ar: "سِعْر", en: "price" },
      { ar: "رَقَم", en: "number" },
      { ar: "رَقَم هاتِف", en: "phone number" },
      { ar: "أَعُدّ", en: "I count" },
      { ar: "تَعُدّ", en: "you count" },
      { ar: "تَعُدّين", en: "you count (f)" },
      { ar: "كُلّ اَلْأَعْداد", en: "all the numbers" },
    ],
  },
  "Natur & Wetter": {
    icon: "🌤️",
    words: [
      { ar: "طَقْس", en: "weather" },
      { ar: "اَلْطَّقْس", en: "the weather" },
      { ar: "مَطَر", en: "rain" },
      { ar: "اَلْمَطَر", en: "the rain" },
      { ar: "مُمْطِر", en: "rainy" },
      { ar: "مُشْمِس", en: "sunny" },
      { ar: "اَلْشَّمْس", en: "the sun" },
      { ar: "اَلْقَمَر", en: "the moon" },
      { ar: "رُطوبة", en: "humidity" },
      { ar: "عالي", en: "high, loud" },
      { ar: "خَفيف", en: "light" },
      { ar: "شِتاء", en: "winter" },
      { ar: "اَلْشِّتاء", en: "the winter" },
      { ar: "صَيْف", en: "summer" },
      { ar: "اَلْصَّيْف", en: "the summer" },
      { ar: "رَبيع", en: "spring" },
      { ar: "اَلْرَّبيع", en: "the spring" },
      { ar: "اَلْخَريف", en: "the fall" },
      { ar: "بَحْر", en: "sea" },
      { ar: "ساحِل", en: "coast" },
      { ar: "اَلْسّاحِل", en: "the coast" },
      { ar: "ساحِلِيّ", en: "coastal" },
      { ar: "جَبَل", en: "mountain" },
      { ar: "مَناظِر", en: "views" },
      { ar: "أَسَد", en: "lion" },
      { ar: "فَأْر", en: "mouse" },
      { ar: "كَلْب", en: "dog" },
      { ar: "قِطّة", en: "cat" },
    ],
  },
  "Transport & Reisen": {
    icon: "✈️",
    words: [
      { ar: "سَفَر", en: "travel" },
      { ar: "رِحْلة", en: "trip" },
      { ar: "جَواز سَفَر", en: "passport" },
      { ar: "تَذْكَرة", en: "ticket" },
      { ar: "أُسافِر", en: "I travel" },
      { ar: "أُخَطِّط", en: "I plan" },
      { ar: "باص", en: "bus" },
      { ar: "قِطار", en: "train" },
      { ar: "سَيّارة", en: "car" },
      { ar: "مَحَطّة", en: "station" },
      { ar: "مَوْقِف", en: "stop" },
      { ar: "مَوْقِع", en: "site" },
      { ar: "مَواقِع", en: "sites" },
      { ar: "بَعيد", en: "far" },
      { ar: "قَريب مِن", en: "close to" },
      { ar: "أَنْطَلِق", en: "I leave" },
      { ar: "آخُذ", en: "I take" },
      { ar: "تَأْخُذ", en: "you/she takes" },
      { ar: "تَأْخُذون", en: "you all take" },
      { ar: "نَأْخُذ", en: "we take" },
      { ar: "يَأْخُذون", en: "they take" },
      { ar: "اَلْسَّفَر إِلى", en: "traveling to" },
      { ar: "تَزور", en: "you/she visits" },
      { ar: "يَزور", en: "he visits" },
      { ar: "أَزور", en: "I visit" },
      { ar: "مَتْحَف", en: "museum" },
      { ar: "مَطْعَم", en: "restaurant" },
      { ar: "سوق", en: "market" },
      { ar: "مَدْرَسة", en: "school" },
      { ar: "جامِعة", en: "university" },
      { ar: "مَكان", en: "place" },
      { ar: "هُنا", en: "here" },
    ],
  },
  "Verben - Alltag": {
    icon: "🏃",
    words: [
      { ar: "أَصْحو", en: "I wake up" },
      { ar: "تَصْحون", en: "you wake up (pl)" },
      { ar: "تَصْحين", en: "you wake up (f)" },
      { ar: "أَنام", en: "I sleep" },
      { ar: "تَنام", en: "you/she sleeps" },
      { ar: "أَلْبَس", en: "I get dressed" },
      { ar: "أَسْتَحِمّ", en: "I shower" },
      { ar: "أُفَرِّش", en: "I brush" },
      { ar: "أَتَناوَل", en: "I eat, have" },
      { ar: "آكُل", en: "I eat" },
      { ar: "يَأْكُل", en: "he eats" },
      { ar: "أَشْرَب", en: "I drink" },
      { ar: "أَكْتُب", en: "I write" },
      { ar: "أَقْرَأ", en: "I read" },
      { ar: "أَسْتَمِع", en: "I listen" },
      { ar: "أُشاهِد", en: "I watch" },
      { ar: "أَذْهَب", en: "I go" },
      { ar: "تَذْهَب", en: "you/she goes" },
      { ar: "سَأَذْهَب", en: "I will go" },
      { ar: "أَجيء", en: "I come" },
      { ar: "تَجيئين", en: "you come (f)" },
      { ar: "أَجِد", en: "I find" },
      { ar: "أَرى", en: "I see" },
      { ar: "أَفْهَم", en: "I understand" },
      { ar: "أَعْرِف", en: "I know" },
      { ar: "لا أَعْرِف", en: "I do not know" },
      { ar: "نَعْرِف", en: "we know" },
      { ar: "تَعْرِف", en: "you/she knows" },
      { ar: "تَعْرِفين", en: "you know (f)" },
      { ar: "تَعْرِفون", en: "you all know" },
      { ar: "يَعْرِفون", en: "they know" },
      { ar: "أَفْتَح", en: "I open" },
      { ar: "اِفْتَح", en: "open (m)" },
      { ar: "اِفْتَحي", en: "open (f)" },
      { ar: "أَدْخُل", en: "I enter" },
      { ar: "يَسْكُن", en: "he lives" },
      { ar: "تَسْكُن", en: "she lives" },
      { ar: "تَسْكُنين", en: "you live (f)" },
      { ar: "أَسْكُن", en: "I live" },
      { ar: "أَحْصُل", en: "obtain" },
      { ar: "أُساعِد", en: "I help" },
    ],
  },
  "Verben - Kommunikation": {
    icon: "💬",
    words: [
      { ar: "أَتَكَلَّم", en: "I speak" },
      { ar: "تَتَكَلَّم", en: "you/she speaks" },
      { ar: "سَأَتَكَلَّم", en: "I will speak" },
      { ar: "اَلْكَلام", en: "talking, to talk" },
      { ar: "أَتَّصِل", en: "I call" },
      { ar: "سَأَتَّصِل", en: "I will call" },
      { ar: "بِٱلْهاتِف", en: "on the phone" },
      { ar: "يَعود", en: "he returns" },
      { ar: "سَيَعود", en: "he will return" },
      { ar: "يَعْني", en: "means" },
      { ar: "أَعْطيني", en: "give me" },
      { ar: "أَعْطِني", en: "give me" },
      { ar: "أَعْطوني", en: "give me (pl)" },
      { ar: "يُعْطون", en: "they give" },
      { ar: "تُعْطين", en: "you give (f)" },
      { ar: "سُؤال", en: "question" },
      { ar: "مَن مَعي", en: "who is this" },
    ],
  },
  "Verben - Wollen & Mögen": {
    icon: "❤️",
    words: [
      { ar: "أُريد", en: "I want" },
      { ar: "تُريد", en: "you/she wants" },
      { ar: "نُريد", en: "we want" },
      { ar: "تُريدون", en: "you all want" },
      { ar: "يُريد", en: "he wants" },
      { ar: "يُريدون", en: "they want" },
      { ar: "أُحِبّ", en: "I love, I like" },
      { ar: "لا أُحِبّ", en: "I do not like" },
      { ar: "تُحِبّ", en: "you/she likes" },
      { ar: "تُحِبّين", en: "you like (f)" },
      { ar: "يُحِبّ", en: "he loves" },
      { ar: "أُفَضِّل", en: "I prefer" },
      { ar: "أَتَمَنّى", en: "I hope" },
      { ar: "أَحْتاج إِلى", en: "I need" },
      { ar: "أَكْرَه", en: "I hate" },
      { ar: "يَجِب أَنْ", en: "need to, must" },
    ],
  },
  "Verben - Sein & Werden": {
    icon: "🔄",
    words: [
      { ar: "أَكون", en: "I am" },
      { ar: "تَكون", en: "you/she/they are" },
      { ar: "تَكوني", en: "you are (f)" },
      { ar: "تَكونوا", en: "you are (pl)" },
      { ar: "أُصْبِح", en: "I become" },
      { ar: "تُصْبِحي", en: "you become (f)" },
      { ar: "تُصْبِحوا", en: "you become (pl)" },
      { ar: "سَأُصْبِح", en: "I will become" },
      { ar: "لَسْتُ", en: "I am not" },
      { ar: "لَسْتَ", en: "you are not" },
      { ar: "لَيْسَ", en: "is not, not" },
      { ar: "لَيْسَت", en: "is not (f)" },
      { ar: "مَوْجود", en: "here, present" },
    ],
  },
  "Verben - Lernen": {
    icon: "📚",
    words: [
      { ar: "أَدْرُس", en: "I study" },
      { ar: "تَدْرُس", en: "she studies" },
      { ar: "تَدْرُسين", en: "you study (f)" },
      { ar: "يَدْرُس", en: "he studies" },
      { ar: "تَعَلُّم", en: "learning, to learn" },
      { ar: "اَلْتَّعَرُّف عَلى", en: "to meet" },
      { ar: "عِلْم اَلْحاسوب", en: "computer science" },
      { ar: "عُلوم", en: "science" },
      { ar: "دَرْس", en: "lesson" },
      { ar: "دُروس", en: "lessons" },
      { ar: "صَفّ", en: "class, grade" },
      { ar: "لُغة", en: "language" },
      { ar: "لُغات", en: "languages" },
      { ar: "بِٱلْلُّغة ٱلْعَرَبِيّة", en: "in Arabic" },
      { ar: "كِتاب", en: "book" },
      { ar: "كُتُب", en: "books" },
      { ar: "رِسالة", en: "letter, message" },
      { ar: "رَسائِل", en: "letters" },
      { ar: "صَحيفة", en: "newspaper" },
    ],
  },
  "Verben - Einkaufen": {
    icon: "🛒",
    words: [
      { ar: "أَشْتَري", en: "I buy" },
      { ar: "تَشْتَرين", en: "you buy (f)" },
      { ar: "باع", en: "sold" },
      { ar: "بيع", en: "selling" },
      { ar: "نُقود", en: "cash, money" },
      { ar: "رَخيص", en: "cheap" },
      { ar: "غالي", en: "expensive" },
    ],
  },
  "Adjektive - Eigenschaften": {
    icon: "⭐",
    words: [
      { ar: "جَميل", en: "beautiful (m)" },
      { ar: "جَميلة", en: "beautiful (f)" },
      { ar: "رائِع", en: "awesome, stunning" },
      { ar: "كَبير", en: "big (m)" },
      { ar: "كَبيرة", en: "big (f)" },
      { ar: "صَغير", en: "small" },
      { ar: "طَويل", en: "long, tall" },
      { ar: "قَصير", en: "short" },
      { ar: "جَديد", en: "new (m)" },
      { ar: "جَديدة", en: "new (f)" },
      { ar: "قَديم", en: "old" },
      { ar: "سَريع", en: "fast (m)" },
      { ar: "سَريعة", en: "fast (f)" },
      { ar: "ثَقيل", en: "heavy" },
      { ar: "مَشْهور", en: "famous (m)" },
      { ar: "مَشْهورة", en: "famous (f)" },
      { ar: "مُهِمّ", en: "important (m)" },
      { ar: "مُهِمّة", en: "important (f)" },
      { ar: "سَهْل", en: "easy (m)" },
      { ar: "سَهْلة", en: "easy (f)" },
      { ar: "صَعْب", en: "difficult" },
      { ar: "أَسْهَل", en: "easier" },
      { ar: "أَصْعَب", en: "more difficult" },
      { ar: "مُخْتَلِف", en: "different" },
      { ar: "مُتَنَوِّع", en: "diverse" },
      { ar: "تاريخِيّ", en: "historic" },
      { ar: "إِسْلامِيّة", en: "Islamic" },
      { ar: "مُزْدَحِمة", en: "crowded" },
    ],
  },
  "Adjektive - Persönlichkeit": {
    icon: "😊",
    words: [
      { ar: "ذَكِيّ", en: "smart (m)" },
      { ar: "ذَكِيّة", en: "smart (f)" },
      { ar: "جَيِّد", en: "good (m)" },
      { ar: "جَيِّدة", en: "good (f)" },
      { ar: "جَيِّداً", en: "well" },
      { ar: "مُمْتاز", en: "amazing (m)" },
      { ar: "مُمْتازة", en: "amazing (f)" },
      { ar: "لَطيفة", en: "kind, nice (f)" },
      { ar: "كَريم", en: "generous" },
      { ar: "مُثَقَّف", en: "cultured" },
      { ar: "حَسّاس", en: "sensitive" },
      { ar: "مُضْحِك", en: "funny" },
      { ar: "مُمِلّ", en: "boring" },
      { ar: "مُزْعِج", en: "annoying" },
      { ar: "قَبيح", en: "ugly" },
      { ar: "غَريب", en: "weird (m)" },
      { ar: "غَريبة", en: "weird (f)" },
      { ar: "عادي", en: "normal, ordinary" },
      { ar: "مُمتِع", en: "entertaining, fun" },
      { ar: "غَنِيّ", en: "rich" },
      { ar: "فَقير", en: "poor" },
      { ar: "أَغْنى", en: "richer" },
      { ar: "أَفْقَر", en: "poorer" },
    ],
  },
  "Adjektive - Gefühle": {
    icon: "💭",
    words: [
      { ar: "سَعيد", en: "happy" },
      { ar: "حَزين", en: "sad" },
      { ar: "تَعْبان", en: "tired" },
      { ar: "نَعْسان", en: "sleepy" },
      { ar: "جَوْعان", en: "hungry (m)" },
      { ar: "جَوْعانة", en: "hungry (f)" },
      { ar: "مُتَحَمِّس", en: "excited" },
      { ar: "جاهِز", en: "ready" },
    ],
  },
  "Pronomen & Fragewörter": {
    icon: "❓",
    words: [
      { ar: "أَنا", en: "I" },
      { ar: "أَنْتَ", en: "you (m)" },
      { ar: "أَنْتِ", en: "you (f)" },
      { ar: "أَنْتُم", en: "you all" },
      { ar: "هُوَّ", en: "he" },
      { ar: "هِيَّ", en: "she" },
      { ar: "هُم", en: "they" },
      { ar: "نَحْنُ", en: "we" },
      { ar: "ما", en: "what, not" },
      { ar: "ماذا", en: "what" },
      { ar: "مَن", en: "who" },
      { ar: "أَيْن", en: "where" },
      { ar: "مَتى", en: "when" },
      { ar: "كَيْف", en: "how" },
      { ar: "لِماذا", en: "why" },
      { ar: "أَيّ", en: "which, any" },
      { ar: "أَيّة", en: "which (f)" },
      { ar: "هَل", en: "is, do, does" },
      { ar: "هٰذا", en: "this (m)" },
      { ar: "هٰذِهِ", en: "this (f)" },
      { ar: "ذٰلِك", en: "that" },
    ],
  },
  "Besitz & Haben": {
    icon: "🔑",
    words: [
      { ar: "عِنْدي", en: "I have" },
      { ar: "عِنْدَك", en: "you have (m)" },
      { ar: "عِنْدِك", en: "you have (f)" },
      { ar: "عِنْدهُ", en: "he has" },
      { ar: "عِنْدها", en: "she has" },
      { ar: "عِنْدنا", en: "we have" },
      { ar: "عِنْدكُم", en: "you all have" },
      { ar: "عِنْدهُم", en: "they have" },
      { ar: "عِنْد", en: "have, has, at" },
      { ar: "لَيْسَ عِنْدي", en: "I do not have" },
      { ar: "لَيْسَ عِنْدَك", en: "you do not have (m)" },
      { ar: "لَيْسَ عِنْدِك", en: "you do not have (f)" },
      { ar: "لَيْسَ عِنْدهُ", en: "he does not have" },
      { ar: "لَيْسَ عِنْدها", en: "she does not have" },
      { ar: "مَعي", en: "with me" },
      { ar: "مَعِك", en: "with you" },
      { ar: "مَعَهُ", en: "with him" },
      { ar: "مَعَها", en: "with her" },
      { ar: "مَعَ", en: "with" },
    ],
  },
  "Präpositionen & Orte": {
    icon: "📍",
    words: [
      { ar: "في", en: "in, at" },
      { ar: "عَلى", en: "on, over" },
      { ar: "إِلى", en: "to, at" },
      { ar: "مِن", en: "from, of" },
      { ar: "عَن", en: "about, for" },
      { ar: "أَمام", en: "in front of" },
      { ar: "أَمامي", en: "in front of me" },
      { ar: "أَمامَك", en: "in front of you" },
      { ar: "خَلْف", en: "behind" },
      { ar: "خَلْفي", en: "behind me" },
      { ar: "خَلْفَك", en: "behind you" },
      { ar: "بِجانِب", en: "next to" },
      { ar: "تَحْت", en: "under" },
      { ar: "قَريب مِن", en: "close to" },
      { ar: "بَعيد", en: "far" },
      { ar: "هُنا", en: "here" },
      { ar: "هُناك", en: "there" },
      { ar: "ها", en: "there" },
    ],
  },
  "Konjunktionen & Adverbien": {
    icon: "🔗",
    words: [
      { ar: "وَ", en: "and" },
      { ar: "و", en: "and" },
      { ar: "أَو", en: "or" },
      { ar: "لٰكِنّ", en: "but" },
      { ar: "أَنْ", en: "that, to" },
      { ar: "إذا", en: "if" },
      { ar: "لِأَنَّ", en: "because" },
      { ar: "لِأَنَّني", en: "because I" },
      { ar: "لِأَنَّهُ", en: "because he" },
      { ar: "لِأَنَّها", en: "because she" },
      { ar: "لِأَنَّك", en: "because you (m)" },
      { ar: "لِأَنِّك", en: "because you (f)" },
      { ar: "بِسَبَب", en: "because of" },
      { ar: "لَنْ", en: "will not" },
      { ar: "كَثيراً", en: "a lot, very much" },
      { ar: "كَثير", en: "a lot of, many" },
      { ar: "أَكْثَر", en: "more" },
      { ar: "جِدّاً", en: "very" },
      { ar: "أَيْضاً", en: "also, too" },
      { ar: "فَقَط", en: "only" },
      { ar: "كُلّ", en: "all, each" },
      { ar: "كُلّ شَيْء", en: "everything" },
      { ar: "نَفْس", en: "same" },
      { ar: "أُخْرى", en: "other, another (f)" },
      { ar: "آخَر", en: "other, another" },
      { ar: "مَعاً", en: "together" },
      { ar: "بِٱلْضَّبْط", en: "exactly" },
      { ar: "طَبْعاً", en: "of course" },
      { ar: "تَماماً", en: "absolutely, totally" },
      { ar: "صَحيح", en: "true, correct" },
      { ar: "غَلَط", en: "wrong" },
      { ar: "بِسُرْعة", en: "quickly" },
      { ar: "نَعَم", en: "yes" },
      { ar: "لا", en: "no" },
      { ar: "بِلا", en: "without" },
      { ar: "لا أَحَد", en: "no one" },
      { ar: "أَبَداً", en: "at all, never" },
      { ar: "لِلْأَسَف", en: "unfortunately" },
      { ar: "مِن اَلْمُمْكِن أَنْ", en: "can" },
      { ar: "كافي", en: "enough" },
      { ar: "كاف", en: "enough" },
    ],
  },
  Alltagsgegenstände: {
    icon: "🎒",
    words: [
      { ar: "هاتِف", en: "phone" },
      { ar: "حاسوب", en: "computer" },
      { ar: "لاب توب", en: "laptop" },
      { ar: "قَلَم", en: "pen, pencil" },
      { ar: "قَلَم رَصاص", en: "pencil" },
      { ar: "دَفْتَر", en: "notebook" },
      { ar: "شَنْطة", en: "bag" },
      { ar: "مَحْفَظة", en: "wallet" },
      { ar: "مِفْتاح", en: "key" },
      { ar: "عِلْكة", en: "chewing gum" },
      { ar: "سي دي", en: "CD" },
      { ar: "كوب", en: "cup, mug" },
      { ar: "تاج", en: "crown" },
    ],
  },
  "Hobbys & Aktivitäten": {
    icon: "🎮",
    words: [
      { ar: "نَشاط", en: "activity" },
      { ar: "أَنْشِطة", en: "activities" },
      { ar: "فِكْرة", en: "idea" },
      { ar: "موسيقى", en: "music" },
      { ar: "فيلْم", en: "film" },
      { ar: "فَنّ", en: "art" },
      { ar: "كُرة اَلْقَدَم", en: "soccer" },
      { ar: "لَعْب", en: "playing" },
      { ar: "اَلْجَري", en: "running" },
      { ar: "اَلْسِّباحة", en: "swimming" },
      { ar: "اَلْكِتابة", en: "writing" },
      { ar: "اَلْقِراءة", en: "reading" },
      { ar: "اَلْنَّوْم", en: "sleeping" },
      { ar: "اَلْتَّصْوير", en: "photography" },
      { ar: "مُشاهَدة", en: "watching" },
      { ar: "عالَم", en: "world" },
      { ar: "حَياة", en: "life" },
      { ar: "مُسْتَقْبَل", en: "future" },
      { ar: "أَخْبار", en: "news" },
    ],
  },
  Namen: {
    icon: "👤",
    words: [
      { ar: "مُحَمَّد", en: "Mohamed" },
      { ar: "عُمَر", en: "Omar" },
      { ar: "إِبْراهيم", en: "Ibrahim" },
      { ar: "مَحْمود", en: "Mahmoud" },
      { ar: "غَسّان", en: "Ghassan" },
      { ar: "تامِر", en: "Tamer" },
      { ar: "فَريد", en: "Farid" },
      { ar: "بَشير", en: "Bashir" },
      { ar: "عَلي", en: "Ali" },
      { ar: "زَيد", en: "Zayd" },
      { ar: "دَوود", en: "David" },
      { ar: "شادي", en: "Shadi" },
      { ar: "رَواد", en: "Rawad" },
      { ar: "سيث", en: "Seth" },
      { ar: "مايْك", en: "Mike" },
      { ar: "جورج", en: "George" },
      { ar: "بوب", en: "Bob" },
      { ar: "سام", en: "Sam" },
      { ar: "جودي", en: "Judy" },
      { ar: "روزا", en: "Rosa" },
      { ar: "ريم", en: "Reem" },
      { ar: "رانْيا", en: "Rania" },
      { ar: "سامْية", en: "Samia" },
      { ar: "مُنيرة", en: "Mounira" },
      { ar: "أَرْوى", en: "Arwa" },
      { ar: "لَمى", en: "Lama" },
      { ar: "زَيْنة", en: "Zeina" },
      { ar: "لَيْلى", en: "Laila" },
      { ar: "مَها", en: "Maha" },
      { ar: "جو", en: "Joe" },
      { ar: "كَري", en: "Carrie" },
      { ar: "دُوو", en: "Duo" },
    ],
  },
  Sonstige: {
    icon: "📝",
    words: [
      { ar: "اِسْم", en: "name" },
      { ar: "اِسْمي", en: "my name" },
      { ar: "اِسْمَك", en: "your name (m)" },
      { ar: "اِسْمِك", en: "your name (f)" },
      { ar: "اِسْمهُ", en: "his name" },
      { ar: "اِسْمها", en: "her name" },
      { ar: "شَيْء", en: "thing, anything" },
      { ar: "مِثْل", en: "like" },
      { ar: "يا", en: "hey, oh" },
      { ar: "ذو", en: "with, of" },
      { ar: "أول", en: "first" },
      { ar: "جُدَد", en: "new (pl)" },
      { ar: "بُيوت", en: "houses" },
      { ar: "شَباب", en: "guys" },
      { ar: "سادة", en: "gentlemen" },
      { ar: "مَلِكة", en: "queen" },
      { ar: "ضَواحي", en: "the suburbs" },
      { ar: "اَلْأَزْهَر", en: "Al-Azhar" },
      { ar: "هارْفارْد", en: "Harvard" },
      { ar: "سيرة", en: "biography" },
      { ar: "شاشة", en: "screen, display" },
      { ar: "طوب", en: "brick" },
      { ar: "مو", en: "mu" },
      { ar: "سوء", en: "bad" },
      { ar: "جاك", en: "jack" },
      { ar: "دور", en: "role, floor, turn" },
      { ar: "رود", en: "rhode" },
      { ar: "ري", en: "watering" },
      { ar: "زار", en: "visited" },
      { ar: "زي", en: "uniform, costume" },
      { ar: "واي", en: "wi" },
      { ar: "سي", en: "c" },
      { ar: "رَ", en: "See" },
      { ar: "توب", en: "laptop" },
      { ar: "طيب", en: "kind" },
    ],
  },
};
