// Vokabeldaten - 922 Wörter in 30 Kategorien mit Transliteration
const vocabulary = {
  "Begrüßungen & Höflichkeit": {
    icon: "👋",
    words: [
      { ar: "مَرْحَباً", en: "hello", tr: "marhaban" },
      { ar: "صَباح اَلْخَيْر", en: "good morning", tr: "sabah al-khayr" },
      { ar: "صَباح اَلْنّور", en: "good morning to you", tr: "sabah an-noor" },
      { ar: "مَساء اَلْخَيْر", en: "good evening", tr: "masa' al-khayr" },
      {
        ar: "مَساء اَلْنّور",
        en: "good evening to you too",
        tr: "masa' an-noor",
      },
      { ar: "أَهْلاً", en: "hello", tr: "ahlan" },
      { ar: "شُكْراً", en: "thank you", tr: "shukran" },
      { ar: "عَفْواً", en: "excuse me, you're welcome", tr: "'afwan" },
      { ar: "مَعَ ٱلْسَّلامة", en: "goodbye", tr: "ma'a as-salama" },
      { ar: "إِلى ٱلْلِّقاء", en: "until next time", tr: "ila al-liqa'" },
      { ar: "يَوْم سَعيد", en: "have a nice day", tr: "yawm sa'id" },
      {
        ar: "اَلْسَّلامُ عَلَيْكُم",
        en: "peace be upon you",
        tr: "as-salamu 'alaykum",
      },
      {
        ar: "وَعَلَيْكُمُ ٱلْسَّلام",
        en: "and upon you be peace",
        tr: "wa 'alaykum as-salam",
      },
      { ar: "إِنْ شاءَ ٱلله", en: "God willing", tr: "in sha' allah" },
      { ar: "اَلْحَمْدُ لِله", en: "praise be to God", tr: "al-hamdu lillah" },
      { ar: "يَلّا", en: "alright", tr: "yalla" },
      { ar: "تَمام", en: "OK", tr: "tamam" },
      { ar: "تَشَرَّفْنا", en: "pleasure to meet you", tr: "tasharrafna" },
      { ar: "كَيْفَك", en: "how are you (m)", tr: "kayfak" },
      { ar: "كَيْفِك", en: "how are you (f)", tr: "kayfik" },
      { ar: "بِخَيْر", en: "well, OK", tr: "bi-khayr" },
      { ar: "تَفَضَّل", en: "go ahead, come in, here you go", tr: "tafaddal" },
      { ar: "تَفَضَّلي", en: "here you go (f)", tr: "tafaddali" },
      { ar: "تَفَضَّلوا", en: "here you go (pl)", tr: "tafaddalu" },
      { ar: "مِن فَضْلِك", en: "please (f)", tr: "min fadlik" },
      { ar: "مِن فَضْلَك", en: "please (m)", tr: "min fadlak" },
      { ar: "أَلو", en: "hello (phone)", tr: "alo" },
      { ar: "آسِف", en: "sorry", tr: "asif" },
      { ar: "تَعالَ", en: "come (m)", tr: "ta'ala" },
      { ar: "تَعالي", en: "come (f)", tr: "ta'ali" },
      { ar: "تَعالوا", en: "come (pl)", tr: "ta'alu" },
      { ar: "اَلله يُسَلِّمَك", en: "thank you", tr: "allah yusallimak" },
      { ar: "اَلله يُسَلِّمِك", en: "thank you (f)", tr: "allah yusallimik" },
      { ar: "سَلامتَك", en: "get better (m)", tr: "salamtak" },
      { ar: "سَلامتِك", en: "get better (f)", tr: "salamtik" },
    ],
  },
  "Familie & Beziehungen": {
    icon: "👨‍👩‍👧‍👦",
    words: [
      { ar: "أَب", en: "father", tr: "ab" },
      { ar: "أُمّ", en: "mother", tr: "umm" },
      { ar: "أَخ", en: "brother", tr: "akh" },
      { ar: "أُخْت", en: "sister", tr: "ukht" },
      { ar: "اِبْن", en: "son", tr: "ibn" },
      { ar: "بِنْت", en: "daughter, a girl", tr: "bint" },
      { ar: "جَدّ", en: "grandfather", tr: "jadd" },
      { ar: "جَدّة", en: "grandmother", tr: "jadda" },
      { ar: "عَمّ", en: "uncle", tr: "'amm" },
      { ar: "خالة", en: "aunt", tr: "khala" },
      { ar: "بِنْت عَمّ", en: "cousin", tr: "bint 'amm" },
      { ar: "زَوْج", en: "husband", tr: "zawj" },
      { ar: "زَوْجة", en: "wife", tr: "zawja" },
      { ar: "عائِلة", en: "family", tr: "'a'ila" },
      { ar: "وَلَد", en: "boy, child", tr: "walad" },
      { ar: "رَجُل", en: "man", tr: "rajul" },
      { ar: "اِمْرَأة", en: "woman", tr: "imra'a" },
      { ar: "صَديق", en: "friend (m)", tr: "sadiq" },
      { ar: "صَديقة", en: "friend (f)", tr: "sadiqa" },
      { ar: "جار", en: "neighbor (m)", tr: "jar" },
      { ar: "جارة", en: "neighbor (f)", tr: "jara" },
      { ar: "زَميل", en: "colleague, classmate", tr: "zamil" },
      { ar: "أَبي", en: "my father", tr: "abi" },
      { ar: "أُمّي", en: "my mother", tr: "ummi" },
      { ar: "أَخي", en: "my brother", tr: "akhi" },
      { ar: "أُخْتي", en: "my sister", tr: "ukhti" },
      { ar: "اِبْني", en: "my son", tr: "ibni" },
      { ar: "بِنْتي", en: "my daughter", tr: "binti" },
      { ar: "جَدّي", en: "my grandfather", tr: "jaddi" },
      { ar: "جَدَّتي", en: "my grandmother", tr: "jaddati" },
      { ar: "زَوْجي", en: "my husband", tr: "zawji" },
      { ar: "زَوْجَتي", en: "my wife", tr: "zawjati" },
      { ar: "أَخو", en: "brother of", tr: "akhu" },
      { ar: "مُتَزَوِّج", en: "married", tr: "mutazawwij" },
      { ar: "مُطَلَّق", en: "divorced", tr: "mutallaq" },
      { ar: "قَريب", en: "relative, close", tr: "qarib" },
      { ar: "أَقارِب", en: "relatives", tr: "aqarib" },
      { ar: "أَصْدِقاء", en: "friends", tr: "asdiqa'" },
      { ar: "ناس", en: "people, folks", tr: "nas" },
    ],
  },
  "Kleidung & Accessoires": {
    icon: "👔",
    words: [
      { ar: "فُسْتان", en: "dress", tr: "fustan" },
      { ar: "فَساتين", en: "dresses", tr: "fasatin" },
      { ar: "بَدْلة", en: "a suit", tr: "badla" },
      { ar: "بَدَلات", en: "suits", tr: "badalat" },
      { ar: "قَميص", en: "shirt", tr: "qamis" },
      { ar: "قُمْصان", en: "shirts", tr: "qumsan" },
      { ar: "مَعاطِف", en: "coats", tr: "ma'atif" },
      { ar: "مِعْطَف", en: "coat", tr: "mi'taf" },
      { ar: "قُفّازات", en: "gloves", tr: "quffazat" },
      { ar: "مَلابِس", en: "clothes", tr: "malabis" },
      { ar: "جَوارِب", en: "socks", tr: "jawarib" },
      { ar: "نَظّارات", en: "glasses", tr: "nazzarat" },
      { ar: "حِذاء", en: "shoes", tr: "hiza'" },
      { ar: "بِنْطال", en: "pants", tr: "bintal" },
      { ar: "حِزام", en: "belt", tr: "hizam" },
      { ar: "سُتْرة", en: "jacket", tr: "sutra" },
      { ar: "بَلوزة", en: "blouse", tr: "bluza" },
      { ar: "تَنّورة", en: "skirt", tr: "tannura" },
      { ar: "تي شيرْت", en: "t-shirt", tr: "ti shert" },
      { ar: "وِشاح", en: "scarf", tr: "wishah" },
      { ar: "قُبَّعة", en: "hat", tr: "qubba'a" },
      { ar: "جاكيت", en: "jacket", tr: "jakit" },
      { ar: "صوف", en: "wool", tr: "suf" },
      { ar: "كُمّ", en: "sleeves", tr: "kumm" },
      { ar: "كُم", en: "sleeves", tr: "kum" },
      { ar: "لابِس", en: "wearing (m)", tr: "labis" },
      { ar: "لابِسة", en: "wearing (f)", tr: "labisa" },
    ],
  },
  Farben: {
    icon: "🎨",
    words: [
      { ar: "لَوْن", en: "color", tr: "lawn" },
      { ar: "وَرْدِيّ", en: "pink", tr: "wardi" },
      { ar: "أَبْيَض", en: "white (m)", tr: "abyad" },
      { ar: "بَيْضاء", en: "white (f)", tr: "bayda'" },
      { ar: "أَزْرَق", en: "blue (m)", tr: "azraq" },
      { ar: "زَرْقاء", en: "blue (f)", tr: "zarqa'" },
      { ar: "بُنِّيّ", en: "brown (m)", tr: "bunni" },
      { ar: "بُنِّيّة", en: "brown (f)", tr: "bunniyya" },
    ],
  },
  "Essen & Trinken": {
    icon: "🍽️",
    words: [
      { ar: "فُطور", en: "breakfast", tr: "futur" },
      { ar: "غَداء", en: "lunch", tr: "ghada'" },
      { ar: "عَشاء", en: "dinner", tr: "'asha'" },
      { ar: "أَكْل", en: "food", tr: "akl" },
      { ar: "خُبْز", en: "bread", tr: "khubz" },
      { ar: "خُبْزاً", en: "bread (acc)", tr: "khubzan" },
      { ar: "رُزّ", en: "rice", tr: "ruzz" },
      { ar: "اَلْرُّزّ", en: "rice", tr: "ar-ruzz" },
      { ar: "سَلَطة", en: "salad", tr: "salata" },
      { ar: "شورْبة", en: "soup", tr: "shorba" },
      { ar: "حُمُّص", en: "hummus", tr: "hummus" },
      { ar: "حُمُّصاً", en: "hummus (acc)", tr: "hummusan" },
      { ar: "فَلافِل", en: "falafel", tr: "falafel" },
      { ar: "كِبّة", en: "kibbeh", tr: "kibbe" },
      { ar: "كَباب", en: "kebab", tr: "kabab" },
      { ar: "كَباباً", en: "kebab (acc)", tr: "kababan" },
      { ar: "تَبّولة", en: "tabbouleh", tr: "tabbule" },
      { ar: "مُقَبِّلات", en: "appetizers", tr: "muqabbilat" },
      { ar: "طَبَق", en: "dish", tr: "tabaq" },
      { ar: "حَلْوى", en: "dessert", tr: "halwa" },
      { ar: "كَعْك", en: "cake", tr: "ka'k" },
      { ar: "سَمَك", en: "fish", tr: "samak" },
      { ar: "دَجاج", en: "chicken", tr: "dajaj" },
      { ar: "بَطاطا", en: "potatoes", tr: "batata" },
      { ar: "جَزَر", en: "carrots", tr: "jazar" },
      { ar: "بَنَدورة", en: "tomatoes", tr: "banadoora" },
      { ar: "كوسا", en: "squash", tr: "kusa" },
      { ar: "بامْيا", en: "okra", tr: "bamya" },
      { ar: "بَصَل", en: "onions", tr: "basal" },
      { ar: "خُضْراوات", en: "vegetables", tr: "khudrawat" },
      { ar: "فاكِهة", en: "fruit", tr: "fakiha" },
      { ar: "موزة", en: "banana", tr: "mawza" },
      { ar: "توت", en: "strawberries, berry", tr: "tut" },
      { ar: "جُبن", en: "cheese", tr: "jubn" },
      { ar: "اَلْثّوم", en: "the garlic", tr: "ath-thum" },
      { ar: "قَهْوة", en: "coffee", tr: "qahwa" },
      { ar: "شاي", en: "tea", tr: "shay" },
      { ar: "شاياً", en: "tea (acc)", tr: "shayan" },
      { ar: "عَصير", en: "juice", tr: "'asir" },
      { ar: "عَصيراً", en: "juice (acc)", tr: "'asiran" },
      { ar: "ماء", en: "water", tr: "ma'" },
      { ar: "حَليب", en: "milk", tr: "halib" },
      { ar: "مَشْروب", en: "drink", tr: "mashrub" },
      { ar: "صِحِّيّ", en: "healthy", tr: "sihhi" },
      { ar: "طازِج", en: "fresh", tr: "tazij" },
      { ar: "حارّ", en: "spicy, hot", tr: "harr" },
      { ar: "بارِد", en: "cold", tr: "barid" },
      { ar: "بارِداً", en: "cold (acc)", tr: "baridan" },
      { ar: "ساخِناً", en: "warm (acc)", tr: "sakhinan" },
      { ar: "طَيِّب", en: "good, kind", tr: "tayyib" },
      { ar: "طَيِّباً", en: "good (acc)", tr: "tayyiban" },
    ],
  },
  "Körper & Gesundheit": {
    icon: "🏥",
    words: [
      { ar: "عَيْن", en: "eye", tr: "'ayn" },
      { ar: "يَد", en: "hand", tr: "yad" },
      { ar: "فَم", en: "mouth", tr: "fam" },
      { ar: "أَسْنان", en: "teeth", tr: "asnan" },
      { ar: "شَعْر", en: "hair", tr: "sha'r" },
      { ar: "طَبيب", en: "doctor", tr: "tabib" },
      { ar: "دُكْتور", en: "doctor", tr: "doktor" },
      { ar: "دُكْتورة", en: "doctor (f)", tr: "doktora" },
      { ar: "مَريض", en: "sick", tr: "marid" },
      { ar: "صُداع", en: "headache", tr: "suda'" },
      { ar: "أَلَم", en: "pain", tr: "alam" },
      { ar: "حَرارة", en: "fever", tr: "harara" },
      { ar: "قَوِيّ", en: "strong", tr: "qawiyy" },
      { ar: "ما بِكَ", en: "what is wrong (m)", tr: "ma bika" },
      { ar: "ما بِكِ", en: "what is wrong (f)", tr: "ma biki" },
      { ar: "أَشْعُر", en: "I feel", tr: "ash'ur" },
      { ar: "تَرْتاحي", en: "you rest (f)", tr: "tartahi" },
      { ar: "تَرْتاحوا", en: "you rest (pl)", tr: "tartahu" },
      { ar: "يَرْتاحوا", en: "they rest", tr: "yartahu" },
      { ar: "أَرْتاح", en: "I rest, I relax", tr: "artah" },
      { ar: "اِسْتِراحة", en: "break", tr: "istiraha" },
      { ar: "صابون", en: "soap", tr: "sabun" },
      { ar: "شامْبو", en: "shampoo", tr: "shambu" },
      { ar: "مَعْجون أَسْنان", en: "toothpaste", tr: "ma'jun asnan" },
      { ar: "فُرْشاة أَسْنان", en: "toothbrush", tr: "furshat asnan" },
      { ar: "رائِحة", en: "smell", tr: "ra'iha" },
      { ar: "فُوَط", en: "towels", tr: "fuwat" },
    ],
  },
  "Berufe & Arbeit": {
    icon: "💼",
    words: [
      { ar: "مِهْنة", en: "a profession", tr: "mihna" },
      { ar: "عَمَل", en: "work, job", tr: "'amal" },
      { ar: "مُدير", en: "manager, director", tr: "mudir" },
      { ar: "مُوَظَّف", en: "employee", tr: "muwazzaf" },
      { ar: "مُهَنْدِس", en: "engineer (m)", tr: "muhandis" },
      { ar: "مُهَنْدِسة", en: "engineer (f)", tr: "muhandisa" },
      { ar: "مُعَلِّم", en: "teacher (m)", tr: "mu'allim" },
      { ar: "مُعَلِّمة", en: "teacher (f)", tr: "mu'allima" },
      { ar: "أُسْتاذ", en: "professor (m)", tr: "ustaz" },
      { ar: "أُسْتاذة", en: "professor (f)", tr: "ustaza" },
      { ar: "مُحامي", en: "lawyer", tr: "muhami" },
      { ar: "مُحاسِب", en: "accountant", tr: "muhasib" },
      { ar: "مُتَرْجِم", en: "translator (m)", tr: "mutarjim" },
      { ar: "مُتَرْجِمة", en: "translator (f)", tr: "mutarjima" },
      { ar: "مُصَوِّر", en: "photographer", tr: "musawwir" },
      { ar: "باحِث", en: "researcher", tr: "bahith" },
      { ar: "طالِب", en: "student", tr: "talib" },
      { ar: "بائِع", en: "vendor", tr: "ba'i'" },
      { ar: "جُنْدِيّ", en: "soldier", tr: "jundi" },
      { ar: "قاضي", en: "judge", tr: "qadi" },
      { ar: "رَبّ بَيْت", en: "homemaker (m)", tr: "rabb bayt" },
      { ar: "رَبّة بَيْت", en: "homemaker (f)", tr: "rabbat bayt" },
      { ar: "مَصْنَع", en: "factory", tr: "masna'" },
      { ar: "شَرِكة", en: "company", tr: "sharika" },
      { ar: "مَكْتَب", en: "office", tr: "maktab" },
      { ar: "أَعْمَل", en: "I work", tr: "a'mal" },
      { ar: "تَعْمَلين", en: "you work (f)", tr: "ta'malin" },
      { ar: "تَعْمَل", en: "you/she works", tr: "ta'mal" },
      { ar: "مَشْغول", en: "busy", tr: "mashghul" },
      { ar: "مُتَفَرِّغ", en: "free", tr: "mutafarrigh" },
    ],
  },
  "Haus & Wohnung": {
    icon: "🏠",
    words: [
      { ar: "بَيْت", en: "house, home", tr: "bayt" },
      { ar: "بيت", en: "house, home", tr: "bayt" },
      { ar: "شَقّة", en: "apartment", tr: "shaqqa" },
      { ar: "غُرْفة", en: "room", tr: "ghurfa" },
      { ar: "غُرْفة نَوْم", en: "bedroom", tr: "ghurfat nawm" },
      { ar: "مَطْبَخ", en: "kitchen", tr: "matbakh" },
      { ar: "حَمّام", en: "bathroom", tr: "hammam" },
      { ar: "صالون", en: "living room", tr: "salun" },
      { ar: "شُرْفة", en: "balcony", tr: "shurfa" },
      { ar: "مَمَرّ", en: "hallway", tr: "mamarr" },
      { ar: "كَراج", en: "garage", tr: "karaj" },
      { ar: "حَديقة", en: "garden", tr: "hadiqa" },
      { ar: "باب", en: "door", tr: "bab" },
      { ar: "شُبّاك", en: "window", tr: "shubbak" },
      { ar: "حائِط", en: "wall", tr: "ha'it" },
      { ar: "سَرير", en: "bed", tr: "sarir" },
      { ar: "كُرْسي", en: "chair", tr: "kursi" },
      { ar: "طاوِلة", en: "table", tr: "tawila" },
      { ar: "تِلْفاز", en: "television", tr: "tilfaz" },
      { ar: "مُلاءات", en: "sheets", tr: "mula'at" },
      { ar: "إيجار", en: "rent", tr: "ijar" },
      { ar: "بِناية", en: "building", tr: "binaya" },
      {
        ar: "في ٱلْطّابِق اَلْأَوَّل",
        en: "on the first floor",
        tr: "fi at-tabiq al-awwal",
      },
      {
        ar: "في ٱلْطّابِق اَلْثّاني",
        en: "the second floor",
        tr: "fi at-tabiq ath-thani",
      },
      { ar: "شارِع", en: "street", tr: "shari'" },
      { ar: "ضَوْء", en: "light", tr: "daw'" },
      { ar: "صَوْت", en: "noise", tr: "sawt" },
      { ar: "ضَجّة", en: "noise", tr: "dajja" },
      { ar: "مُشْكِلة", en: "problem", tr: "mushkila" },
      { ar: "مَكْسور", en: "broken", tr: "maksur" },
      { ar: "مُعَطَّل", en: "out of order", tr: "mu'attal" },
      { ar: "نَظيف", en: "clean", tr: "nazif" },
      { ar: "وَسِخ", en: "dirty", tr: "wasikh" },
      { ar: "واسِع", en: "spacious (m)", tr: "wasi'" },
      { ar: "واسِعة", en: "spacious (f)", tr: "wasi'a" },
      { ar: "مَسْبَح", en: "swimming pool", tr: "masbah" },
      { ar: "صالة رِياضِيّة", en: "gym", tr: "salat riyadiyya" },
      { ar: "فُنْدُق", en: "hotel", tr: "funduq" },
      { ar: "حَجْز", en: "reservation", tr: "hajz" },
      { ar: "مَمْنوع", en: "forbidden", tr: "mamnu'" },
    ],
  },
  "Länder & Städte": {
    icon: "🌍",
    words: [
      { ar: "بَلَد", en: "country", tr: "balad" },
      { ar: "بِلاد", en: "countries", tr: "bilad" },
      { ar: "مَدينة", en: "city", tr: "madina" },
      { ar: "عاصِمة", en: "capital", tr: "'asima" },
      { ar: "قَرْية", en: "village", tr: "qarya" },
      { ar: "وِلاية", en: "state", tr: "wilaya" },
      { ar: "جَزيرة", en: "island", tr: "jazira" },
      { ar: "مِصْر", en: "Egypt", tr: "misr" },
      { ar: "اَلْقاهِرة", en: "Cairo", tr: "al-qahira" },
      { ar: "سوريا", en: "Syria", tr: "suriya" },
      { ar: "دِمَشْق", en: "Damascus", tr: "dimashq" },
      { ar: "لُبْنان", en: "Lebanon", tr: "lubnan" },
      { ar: "بَيْروت", en: "Beirut", tr: "bayrut" },
      { ar: "اَلْعِراق", en: "Iraq", tr: "al-'iraq" },
      { ar: "بَغْداد", en: "Baghdad", tr: "baghdad" },
      { ar: "فِلَسْطين", en: "Palestine", tr: "filastin" },
      { ar: "اَلْأُرْدُن", en: "Jordan", tr: "al-urdun" },
      { ar: "اَلْيَمَن", en: "Yemen", tr: "al-yaman" },
      { ar: "اَلْسّودان", en: "Sudan", tr: "as-sudan" },
      { ar: "اَلْخَرطوم", en: "Khartoum", tr: "al-khartum" },
      { ar: "عُمان", en: "Oman", tr: "'uman" },
      { ar: "تونِس", en: "Tunisia", tr: "tunis" },
      { ar: "مالْطا", en: "Malta", tr: "malta" },
      { ar: "أوروبّا", en: "Europe", tr: "urubba" },
      { ar: "آسْيا", en: "Asia", tr: "asya" },
      { ar: "أَمريكا", en: "America", tr: "amrika" },
      { ar: "فَرَنْسا", en: "France", tr: "faransa" },
      { ar: "باريس", en: "Paris", tr: "baris" },
      { ar: "أَلْمانْيا", en: "Germany", tr: "almanya" },
      { ar: "بَرْلين", en: "Berlin", tr: "barlin" },
      { ar: "إِنْجِلْتِرا", en: "England", tr: "injiltira" },
      { ar: "إِسْكُتْلَنْدا", en: "Scotland", tr: "iskutlanda" },
      { ar: "هولَنْدا", en: "Holland", tr: "holanda" },
      { ar: "أَمْسْتِرْدام", en: "Amsterdam", tr: "amsterdam" },
      { ar: "كَنَدا", en: "Canada", tr: "kanada" },
      { ar: "أُسْتُرالْيا", en: "Australia", tr: "ustralya" },
      { ar: "إيطالْيا", en: "Italy", tr: "italya" },
      { ar: "اَلْصّين", en: "China", tr: "as-sin" },
      { ar: "نْيويورْك", en: "New York", tr: "nyuyork" },
      { ar: "كوبا", en: "Cuba", tr: "kuba" },
      { ar: "بيرو", en: "Peru", tr: "biru" },
      { ar: "كوريا", en: "Korea", tr: "kuriya" },
      { ar: "ريجا", en: "Riga", tr: "riga" },
      { ar: "باكو", en: "Baku", tr: "baku" },
      { ar: "داكار", en: "Dakar", tr: "dakar" },
      { ar: "جوبا", en: "Juba", tr: "juba" },
      { ar: "اَلْإِسْكَنْدَرِيّة", en: "Alexandria", tr: "al-iskandariyya" },
      {
        ar: "وِلاية جورْجْيا",
        en: "the state of Georgia",
        tr: "wilayat jorjya",
      },
      {
        ar: "مَدينة لوس أَنْجِلِس",
        en: "the city of Los Angeles",
        tr: "madinat los anjilis",
      },
      {
        ar: "وِلاية كاليفورْنْيا",
        en: "the state of California",
        tr: "wilayat kaliforniya",
      },
      { ar: "مَدينة سافانا", en: "the city of Savannah", tr: "madinat safana" },
      {
        ar: "اَلْبَحْر اَلْأَبْيَض اَلْمُتَوَسِّط",
        en: "the Mediterranean Sea",
        tr: "al-bahr al-abyad al-mutawassit",
      },
    ],
  },
  Nationalitäten: {
    icon: "🏳️",
    words: [
      { ar: "عَرَبِيّ", en: "Arab (m)", tr: "'arabi" },
      { ar: "عَرَبِيّة", en: "Arab (f), Arabic", tr: "'arabiyya" },
      { ar: "مِصْرِيّ", en: "Egyptian (m)", tr: "misri" },
      { ar: "سورِيّ", en: "Syrian (m)", tr: "suri" },
      { ar: "سورِيّة", en: "Syrian (f)", tr: "suriyya" },
      { ar: "لُبنانِيّ", en: "Lebanese (m)", tr: "lubnani" },
      { ar: "لُبْنانِيّة", en: "Lebanese (f)", tr: "lubnaniyya" },
      { ar: "أُرْدُنِيّ", en: "Jordanian (m)", tr: "urduni" },
      { ar: "أُرْدُنِيّة", en: "Jordanian (f)", tr: "urduniyya" },
      { ar: "فِلَسْطينِيّة", en: "Palestinian (f)", tr: "filastiniyya" },
      { ar: "عُمانِيّ", en: "Omani", tr: "'umani" },
      { ar: "تونِسِيّ", en: "Tunisian (m)", tr: "tunisi" },
      { ar: "تونِسِيّة", en: "Tunisian (f)", tr: "tunisiyya" },
      { ar: "مَغْرِبِيّ", en: "Moroccan (m)", tr: "maghribi" },
      { ar: "مَغْرِبِيّة", en: "Moroccan (f)", tr: "maghribiyya" },
      { ar: "أَمريكِيّ", en: "American (m)", tr: "amriki" },
      { ar: "أَمْريكِيّة", en: "American (f)", tr: "amrikiyya" },
      { ar: "فَرَنْسِيّ", en: "French (m)", tr: "faransi" },
      { ar: "فَرَنْسِيّة", en: "French (f)", tr: "faransiyya" },
      { ar: "إِنْجِليزِيّ", en: "English", tr: "injilizi" },
      { ar: "إِسْكُتْلَنْدِيّ", en: "Scottish", tr: "iskutlandi" },
      { ar: "هولَنْدِيّ", en: "Dutch", tr: "holandi" },
      { ar: "كَنَدِيّ", en: "Canadian", tr: "kanadi" },
    ],
  },
  "Zeit & Kalender": {
    icon: "🕐",
    words: [
      { ar: "وَقْت", en: "time", tr: "waqt" },
      { ar: "ساعة", en: "time, watch, one hour", tr: "sa'a" },
      { ar: "يَوْم", en: "day", tr: "yawm" },
      { ar: "أُسْبوع", en: "week", tr: "usbu'" },
      { ar: "شَهْر", en: "month", tr: "shahr" },
      { ar: "سَنة", en: "year", tr: "sana" },
      { ar: "صَباح", en: "morning", tr: "sabah" },
      { ar: "مَساء", en: "evening", tr: "masa'" },
      { ar: "صَباحاً", en: "in the morning", tr: "sabahan" },
      { ar: "مَساءً", en: "in the evening", tr: "masa'an" },
      { ar: "بِالْلَّيْل", en: "at night", tr: "bil-layl" },
      { ar: "بَعْد اَلْظُّهْر", en: "in the afternoon", tr: "ba'd az-zuhr" },
      { ar: "اَلْيَوْم", en: "today", tr: "al-yawm" },
      { ar: "أَمْس", en: "yesterday", tr: "ams" },
      { ar: "قَبْل", en: "before", tr: "qabl" },
      { ar: "بَعْد", en: "after", tr: "ba'd" },
      { ar: "مُنْذُ", en: "for, since, ago", tr: "munzu" },
      { ar: "لاحِقاً", en: "later", tr: "lahiqan" },
      { ar: "قَريباً", en: "soon", tr: "qariban" },
      { ar: "دائِماً", en: "always", tr: "da'iman" },
      { ar: "أَحْياناً", en: "sometimes", tr: "ahyanan" },
      { ar: "عادةً", en: "usually", tr: "'adatan" },
      { ar: "مُبَكِّراً", en: "early", tr: "mubakkiran" },
      { ar: "في ساعة مُتَأَخِّرة", en: "late", tr: "fi sa'a muta'akhkhira" },
      { ar: "لَحْظة", en: "one moment", tr: "lahza" },
      { ar: "مَرّة", en: "time, once", tr: "marra" },
      { ar: "مَرّة أُخْرى", en: "again", tr: "marra ukhra" },
      { ar: "مَوْعِد", en: "appointment", tr: "maw'id" },
      { ar: "نِهاية اَلْأُسْبوع", en: "weekend", tr: "nihayat al-usbu'" },
      { ar: "اَلْآن", en: "now", tr: "al-an" },
      { ar: "اَلآن", en: "now", tr: "al-an" },
      { ar: "رَمَضان", en: "Ramadan", tr: "ramadan" },
    ],
  },
  Uhrzeiten: {
    icon: "⏰",
    words: [
      { ar: "كَم اَلْسّاعة", en: "what time is it", tr: "kam as-sa'a" },
      { ar: "في أَيّة ساعة", en: "at what time", tr: "fi ayya sa'a" },
      { ar: "نُصْف", en: "half", tr: "nusf" },
      { ar: "اَلْسّاعة ٱلْواحِدة", en: "one o'clock", tr: "as-sa'a al-wahida" },
      {
        ar: "اَلْسّاعة ٱلْثّانْية",
        en: "two o'clock",
        tr: "as-sa'a ath-thaniya",
      },
      {
        ar: "اَلْسّاعة ٱلْثّالِثة",
        en: "three o'clock",
        tr: "as-sa'a ath-thalitha",
      },
      {
        ar: "اَلْسّاعة ٱلْرّابِعة",
        en: "four o'clock",
        tr: "as-sa'a ar-rabi'a",
      },
      {
        ar: "اَلْسّاعة ٱلْخامِسة",
        en: "five o'clock",
        tr: "as-sa'a al-khamisa",
      },
      {
        ar: "اَلْسّاعة ٱلْسّادِسة",
        en: "six o'clock",
        tr: "as-sa'a as-sadisa",
      },
      {
        ar: "اَلْسّاعة ٱلْسّابِعة",
        en: "seven o'clock",
        tr: "as-sa'a as-sabi'a",
      },
      {
        ar: "اَلْسّاعة ٱلْثّامِنة",
        en: "eight o'clock",
        tr: "as-sa'a ath-thamina",
      },
      {
        ar: "اَلْسّاعة ٱلْتّاسِعة",
        en: "nine o'clock",
        tr: "as-sa'a at-tasi'a",
      },
      {
        ar: "اَلْسّاعة ٱلْعاشِرة",
        en: "ten o'clock",
        tr: "as-sa'a al-'ashira",
      },
      {
        ar: "اَلْسّاعة ٱلْحادْية عَشْرة",
        en: "eleven o'clock",
        tr: "as-sa'a al-hadiya 'ashara",
      },
      {
        ar: "اَلْسّاعة ٱلْثّانْية عَشْرة",
        en: "twelve o'clock",
        tr: "as-sa'a ath-thaniya 'ashara",
      },
    ],
  },
  Zahlen: {
    icon: "🔢",
    words: [
      { ar: "٠", en: "0", tr: "sifr" },
      { ar: "١", en: "1", tr: "wahid" },
      { ar: "٢", en: "2", tr: "ithnayn" },
      { ar: "٣", en: "3", tr: "thalatha" },
      { ar: "٤", en: "4", tr: "arba'a" },
      { ar: "٥", en: "5", tr: "khamsa" },
      { ar: "٦", en: "6", tr: "sitta" },
      { ar: "٧", en: "7", tr: "sab'a" },
      { ar: "٨", en: "8", tr: "thamaniya" },
      { ar: "٩", en: "9", tr: "tis'a" },
      { ar: "١٠", en: "10", tr: "'ashara" },
      { ar: "واحِد", en: "one", tr: "wahid" },
      { ar: "كيلو", en: "kilo", tr: "kilu" },
      { ar: "دينار", en: "dinar", tr: "dinar" },
      { ar: "دَنانير", en: "dinars", tr: "dananir" },
      { ar: "بِكَم", en: "how much", tr: "bikam" },
      { ar: "سِعْر", en: "price", tr: "si'r" },
      { ar: "رَقَم", en: "number", tr: "raqam" },
      { ar: "رَقَم هاتِف", en: "phone number", tr: "raqam hatif" },
      { ar: "أَعُدّ", en: "I count", tr: "a'udd" },
      { ar: "تَعُدّ", en: "you count", tr: "ta'udd" },
      { ar: "تَعُدّين", en: "you count (f)", tr: "ta'uddin" },
      { ar: "كُلّ اَلْأَعْداد", en: "all the numbers", tr: "kull al-a'dad" },
    ],
  },
  "Natur & Wetter": {
    icon: "🌤️",
    words: [
      { ar: "طَقْس", en: "weather", tr: "taqs" },
      { ar: "اَلْطَّقْس", en: "the weather", tr: "at-taqs" },
      { ar: "مَطَر", en: "rain", tr: "matar" },
      { ar: "اَلْمَطَر", en: "the rain", tr: "al-matar" },
      { ar: "مُمْطِر", en: "rainy", tr: "mumtir" },
      { ar: "مُشْمِس", en: "sunny", tr: "mushmis" },
      { ar: "اَلْشَّمْس", en: "the sun", tr: "ash-shams" },
      { ar: "اَلْقَمَر", en: "the moon", tr: "al-qamar" },
      { ar: "رُطوبة", en: "humidity", tr: "rutuba" },
      { ar: "عالي", en: "high, loud", tr: "'ali" },
      { ar: "خَفيف", en: "light", tr: "khafif" },
      { ar: "شِتاء", en: "winter", tr: "shita'" },
      { ar: "اَلْشِّتاء", en: "the winter", tr: "ash-shita'" },
      { ar: "صَيْف", en: "summer", tr: "sayf" },
      { ar: "اَلْصَّيْف", en: "the summer", tr: "as-sayf" },
      { ar: "رَبيع", en: "spring", tr: "rabi'" },
      { ar: "اَلْرَّبيع", en: "the spring", tr: "ar-rabi'" },
      { ar: "اَلْخَريف", en: "the fall", tr: "al-kharif" },
      { ar: "بَحْر", en: "sea", tr: "bahr" },
      { ar: "ساحِل", en: "coast", tr: "sahil" },
      { ar: "اَلْسّاحِل", en: "the coast", tr: "as-sahil" },
      { ar: "ساحِلِيّ", en: "coastal", tr: "sahili" },
      { ar: "جَبَل", en: "mountain", tr: "jabal" },
      { ar: "مَناظِر", en: "views", tr: "manazir" },
      { ar: "أَسَد", en: "lion", tr: "asad" },
      { ar: "فَأْر", en: "mouse", tr: "fa'r" },
      { ar: "كَلْب", en: "dog", tr: "kalb" },
      { ar: "قِطّة", en: "cat", tr: "qitta" },
    ],
  },
  "Transport & Reisen": {
    icon: "✈️",
    words: [
      { ar: "سَفَر", en: "travel", tr: "safar" },
      { ar: "رِحْلة", en: "trip", tr: "rihla" },
      { ar: "جَواز سَفَر", en: "passport", tr: "jawaz safar" },
      { ar: "تَذْكَرة", en: "ticket", tr: "tazkara" },
      { ar: "أُسافِر", en: "I travel", tr: "usafir" },
      { ar: "أُخَطِّط", en: "I plan", tr: "ukhattit" },
      { ar: "باص", en: "bus", tr: "bas" },
      { ar: "قِطار", en: "train", tr: "qitar" },
      { ar: "سَيّارة", en: "car", tr: "sayyara" },
      { ar: "مَحَطّة", en: "station", tr: "mahatta" },
      { ar: "مَوْقِف", en: "stop", tr: "mawqif" },
      { ar: "مَوْقِع", en: "site", tr: "mawqi'" },
      { ar: "مَواقِع", en: "sites", tr: "mawaqi'" },
      { ar: "بَعيد", en: "far", tr: "ba'id" },
      { ar: "قَريب مِن", en: "close to", tr: "qarib min" },
      { ar: "أَنْطَلِق", en: "I leave", tr: "antaliq" },
      { ar: "آخُذ", en: "I take", tr: "akhuz" },
      { ar: "تَأْخُذ", en: "you/she takes", tr: "ta'khuz" },
      { ar: "تَأْخُذون", en: "you all take", tr: "ta'khuzun" },
      { ar: "نَأْخُذ", en: "we take", tr: "na'khuz" },
      { ar: "يَأْخُذون", en: "they take", tr: "ya'khuzun" },
      { ar: "اَلْسَّفَر إِلى", en: "traveling to", tr: "as-safar ila" },
      { ar: "تَزور", en: "you/she visits", tr: "tazur" },
      { ar: "يَزور", en: "he visits", tr: "yazur" },
      { ar: "أَزور", en: "I visit", tr: "azur" },
      { ar: "مَتْحَف", en: "museum", tr: "mathaf" },
      { ar: "مَطْعَم", en: "restaurant", tr: "mat'am" },
      { ar: "سوق", en: "market", tr: "suq" },
      { ar: "مَدْرَسة", en: "school", tr: "madrasa" },
      { ar: "جامِعة", en: "university", tr: "jami'a" },
      { ar: "مَكان", en: "place", tr: "makan" },
      { ar: "هُنا", en: "here", tr: "huna" },
    ],
  },
  "Verben - Alltag": {
    icon: "🏃",
    words: [
      { ar: "أَصْحو", en: "I wake up", tr: "ashu" },
      { ar: "تَصْحون", en: "you wake up (pl)", tr: "tashun" },
      { ar: "تَصْحين", en: "you wake up (f)", tr: "tashin" },
      { ar: "أَنام", en: "I sleep", tr: "anam" },
      { ar: "تَنام", en: "you/she sleeps", tr: "tanam" },
      { ar: "أَلْبَس", en: "I get dressed", tr: "albas" },
      { ar: "أَسْتَحِمّ", en: "I shower", tr: "astahimm" },
      { ar: "أُفَرِّش", en: "I brush", tr: "ufarrish" },
      { ar: "أَتَناوَل", en: "I eat, have", tr: "atanawwal" },
      { ar: "آكُل", en: "I eat", tr: "akul" },
      { ar: "يَأْكُل", en: "he eats", tr: "ya'kul" },
      { ar: "أَشْرَب", en: "I drink", tr: "ashrab" },
      { ar: "أَكْتُب", en: "I write", tr: "aktub" },
      { ar: "أَقْرَأ", en: "I read", tr: "aqra'" },
      { ar: "أَسْتَمِع", en: "I listen", tr: "astami'" },
      { ar: "أُشاهِد", en: "I watch", tr: "ushahid" },
      { ar: "أَذْهَب", en: "I go", tr: "azhab" },
      { ar: "تَذْهَب", en: "you/she goes", tr: "tazhab" },
      { ar: "سَأَذْهَب", en: "I will go", tr: "sa-azhab" },
      { ar: "أَجيء", en: "I come", tr: "aji'" },
      { ar: "تَجيئين", en: "you come (f)", tr: "taji'in" },
      { ar: "أَجِد", en: "I find", tr: "ajid" },
      { ar: "أَرى", en: "I see", tr: "ara" },
      { ar: "أَفْهَم", en: "I understand", tr: "afham" },
      { ar: "أَعْرِف", en: "I know", tr: "a'rif" },
      { ar: "لا أَعْرِف", en: "I do not know", tr: "la a'rif" },
      { ar: "نَعْرِف", en: "we know", tr: "na'rif" },
      { ar: "تَعْرِف", en: "you/she knows", tr: "ta'rif" },
      { ar: "تَعْرِفين", en: "you know (f)", tr: "ta'rifin" },
      { ar: "تَعْرِفون", en: "you all know", tr: "ta'rifun" },
      { ar: "يَعْرِفون", en: "they know", tr: "ya'rifun" },
      { ar: "أَفْتَح", en: "I open", tr: "aftah" },
      { ar: "اِفْتَح", en: "open (m)", tr: "iftah" },
      { ar: "اِفْتَحي", en: "open (f)", tr: "iftahi" },
      { ar: "أَدْخُل", en: "I enter", tr: "adkhul" },
      { ar: "يَسْكُن", en: "he lives", tr: "yaskun" },
      { ar: "تَسْكُن", en: "she lives", tr: "taskun" },
      { ar: "تَسْكُنين", en: "you live (f)", tr: "taskunin" },
      { ar: "أَسْكُن", en: "I live", tr: "askun" },
      { ar: "أَحْصُل", en: "obtain", tr: "ahsul" },
      { ar: "أُساعِد", en: "I help", tr: "usa'id" },
    ],
  },
  "Verben - Kommunikation": {
    icon: "💬",
    words: [
      { ar: "أَتَكَلَّم", en: "I speak", tr: "atakallam" },
      { ar: "تَتَكَلَّم", en: "you/she speaks", tr: "tatakallam" },
      { ar: "سَأَتَكَلَّم", en: "I will speak", tr: "sa-atakallam" },
      { ar: "اَلْكَلام", en: "talking, to talk", tr: "al-kalam" },
      { ar: "أَتَّصِل", en: "I call", tr: "attasil" },
      { ar: "سَأَتَّصِل", en: "I will call", tr: "sa-attasil" },
      { ar: "بِٱلْهاتِف", en: "on the phone", tr: "bil-hatif" },
      { ar: "يَعود", en: "he returns", tr: "ya'ud" },
      { ar: "سَيَعود", en: "he will return", tr: "sa-ya'ud" },
      { ar: "يَعْني", en: "means", tr: "ya'ni" },
      { ar: "أَعْطيني", en: "give me", tr: "a'tini" },
      { ar: "أَعْطِني", en: "give me", tr: "a'tini" },
      { ar: "أَعْطوني", en: "give me (pl)", tr: "a'tuni" },
      { ar: "يُعْطون", en: "they give", tr: "yu'tun" },
      { ar: "تُعْطين", en: "you give (f)", tr: "tu'tin" },
      { ar: "سُؤال", en: "question", tr: "su'al" },
      { ar: "مَن مَعي", en: "who is this", tr: "man ma'i" },
    ],
  },
  "Verben - Wollen & Mögen": {
    icon: "❤️",
    words: [
      { ar: "أُريد", en: "I want", tr: "urid" },
      { ar: "تُريد", en: "you/she wants", tr: "turid" },
      { ar: "نُريد", en: "we want", tr: "nurid" },
      { ar: "تُريدون", en: "you all want", tr: "turidun" },
      { ar: "يُريد", en: "he wants", tr: "yurid" },
      { ar: "يُريدون", en: "they want", tr: "yuridun" },
      { ar: "أُحِبّ", en: "I love, I like", tr: "uhibb" },
      { ar: "لا أُحِبّ", en: "I do not like", tr: "la uhibb" },
      { ar: "تُحِبّ", en: "you/she likes", tr: "tuhibb" },
      { ar: "تُحِبّين", en: "you like (f)", tr: "tuhibbin" },
      { ar: "يُحِبّ", en: "he loves", tr: "yuhibb" },
      { ar: "أُفَضِّل", en: "I prefer", tr: "ufaddil" },
      { ar: "أَتَمَنّى", en: "I hope", tr: "atamanna" },
      { ar: "أَحْتاج إِلى", en: "I need", tr: "ahtaj ila" },
      { ar: "أَكْرَه", en: "I hate", tr: "akrah" },
      { ar: "يَجِب أَنْ", en: "need to, must", tr: "yajib an" },
    ],
  },
  "Verben - Sein & Werden": {
    icon: "🔄",
    words: [
      { ar: "أَكون", en: "I am", tr: "akun" },
      { ar: "تَكون", en: "you/she/they are", tr: "takun" },
      { ar: "تَكوني", en: "you are (f)", tr: "takuni" },
      { ar: "تَكونوا", en: "you are (pl)", tr: "takunu" },
      { ar: "أُصْبِح", en: "I become", tr: "usbih" },
      { ar: "تُصْبِحي", en: "you become (f)", tr: "tusbihi" },
      { ar: "تُصْبِحوا", en: "you become (pl)", tr: "tusbihu" },
      { ar: "سَأُصْبِح", en: "I will become", tr: "sa-usbih" },
      { ar: "لَسْتُ", en: "I am not", tr: "lastu" },
      { ar: "لَسْتَ", en: "you are not", tr: "lasta" },
      { ar: "لَيْسَ", en: "is not, not", tr: "laysa" },
      { ar: "لَيْسَت", en: "is not (f)", tr: "laysat" },
      { ar: "مَوْجود", en: "here, present", tr: "mawjud" },
    ],
  },
  "Verben - Lernen": {
    icon: "📚",
    words: [
      { ar: "أَدْرُس", en: "I study", tr: "adrus" },
      { ar: "تَدْرُس", en: "she studies", tr: "tadrus" },
      { ar: "تَدْرُسين", en: "you study (f)", tr: "tadrusin" },
      { ar: "يَدْرُس", en: "he studies", tr: "yadrus" },
      { ar: "تَعَلُّم", en: "learning, to learn", tr: "ta'allum" },
      { ar: "اَلْتَّعَرُّف عَلى", en: "to meet", tr: "at-ta'arruf 'ala" },
      { ar: "عِلْم اَلْحاسوب", en: "computer science", tr: "'ilm al-hasub" },
      { ar: "عُلوم", en: "science", tr: "'ulum" },
      { ar: "دَرْس", en: "lesson", tr: "dars" },
      { ar: "دُروس", en: "lessons", tr: "durus" },
      { ar: "صَفّ", en: "class, grade", tr: "saff" },
      { ar: "لُغة", en: "language", tr: "lugha" },
      { ar: "لُغات", en: "languages", tr: "lughat" },
      {
        ar: "بِٱلْلُّغة ٱلْعَرَبِيّة",
        en: "in Arabic",
        tr: "bil-lugha al-'arabiyya",
      },
      { ar: "كِتاب", en: "book", tr: "kitab" },
      { ar: "كُتُب", en: "books", tr: "kutub" },
      { ar: "رِسالة", en: "letter, message", tr: "risala" },
      { ar: "رَسائِل", en: "letters", tr: "rasa'il" },
      { ar: "صَحيفة", en: "newspaper", tr: "sahifa" },
    ],
  },
  "Verben - Einkaufen": {
    icon: "🛒",
    words: [
      { ar: "أَشْتَري", en: "I buy", tr: "ashtari" },
      { ar: "تَشْتَرين", en: "you buy (f)", tr: "tashtarin" },
      { ar: "باع", en: "sold", tr: "ba'" },
      { ar: "بيع", en: "selling", tr: "bay'" },
      { ar: "نُقود", en: "cash, money", tr: "nuqud" },
      { ar: "رَخيص", en: "cheap", tr: "rakhis" },
      { ar: "غالي", en: "expensive", tr: "ghali" },
    ],
  },
  "Adjektive - Eigenschaften": {
    icon: "⭐",
    words: [
      { ar: "جَميل", en: "beautiful (m)", tr: "jamil" },
      { ar: "جَميلة", en: "beautiful (f)", tr: "jamila" },
      { ar: "رائِع", en: "awesome, stunning", tr: "ra'i'" },
      { ar: "كَبير", en: "big (m)", tr: "kabir" },
      { ar: "كَبيرة", en: "big (f)", tr: "kabira" },
      { ar: "صَغير", en: "small", tr: "saghir" },
      { ar: "طَويل", en: "long, tall", tr: "tawil" },
      { ar: "قَصير", en: "short", tr: "qasir" },
      { ar: "جَديد", en: "new (m)", tr: "jadid" },
      { ar: "جَديدة", en: "new (f)", tr: "jadida" },
      { ar: "قَديم", en: "old", tr: "qadim" },
      { ar: "سَريع", en: "fast (m)", tr: "sari'" },
      { ar: "سَريعة", en: "fast (f)", tr: "sari'a" },
      { ar: "ثَقيل", en: "heavy", tr: "thaqil" },
      { ar: "مَشْهور", en: "famous (m)", tr: "mashhur" },
      { ar: "مَشْهورة", en: "famous (f)", tr: "mashhura" },
      { ar: "مُهِمّ", en: "important (m)", tr: "muhimm" },
      { ar: "مُهِمّة", en: "important (f)", tr: "muhimma" },
      { ar: "سَهْل", en: "easy (m)", tr: "sahl" },
      { ar: "سَهْلة", en: "easy (f)", tr: "sahla" },
      { ar: "صَعْب", en: "difficult", tr: "sa'b" },
      { ar: "أَسْهَل", en: "easier", tr: "ashal" },
      { ar: "أَصْعَب", en: "more difficult", tr: "as'ab" },
      { ar: "مُخْتَلِف", en: "different", tr: "mukhtalif" },
      { ar: "مُتَنَوِّع", en: "diverse", tr: "mutanawwi'" },
      { ar: "تاريخِيّ", en: "historic", tr: "tarikhi" },
      { ar: "إِسْلامِيّة", en: "Islamic", tr: "islamiyya" },
      { ar: "مُزْدَحِمة", en: "crowded", tr: "muzdahima" },
    ],
  },
  "Adjektive - Persönlichkeit": {
    icon: "😊",
    words: [
      { ar: "ذَكِيّ", en: "smart (m)", tr: "zaki" },
      { ar: "ذَكِيّة", en: "smart (f)", tr: "zakiyya" },
      { ar: "جَيِّد", en: "good (m)", tr: "jayyid" },
      { ar: "جَيِّدة", en: "good (f)", tr: "jayyida" },
      { ar: "جَيِّداً", en: "well", tr: "jayyidan" },
      { ar: "مُمْتاز", en: "amazing (m)", tr: "mumtaz" },
      { ar: "مُمْتازة", en: "amazing (f)", tr: "mumtaza" },
      { ar: "لَطيفة", en: "kind, nice (f)", tr: "latifa" },
      { ar: "كَريم", en: "generous", tr: "karim" },
      { ar: "مُثَقَّف", en: "cultured", tr: "muthaqqaf" },
      { ar: "حَسّاس", en: "sensitive", tr: "hassas" },
      { ar: "مُضْحِك", en: "funny", tr: "mudhik" },
      { ar: "مُمِلّ", en: "boring", tr: "mumill" },
      { ar: "مُزْعِج", en: "annoying", tr: "muz'ij" },
      { ar: "قَبيح", en: "ugly", tr: "qabih" },
      { ar: "غَريب", en: "weird (m)", tr: "gharib" },
      { ar: "غَريبة", en: "weird (f)", tr: "ghariba" },
      { ar: "عادي", en: "normal, ordinary", tr: "'adi" },
      { ar: "مُمتِع", en: "entertaining, fun", tr: "mumti'" },
      { ar: "غَنِيّ", en: "rich", tr: "ghani" },
      { ar: "فَقير", en: "poor", tr: "faqir" },
      { ar: "أَغْنى", en: "richer", tr: "aghna" },
      { ar: "أَفْقَر", en: "poorer", tr: "afqar" },
    ],
  },
  "Adjektive - Gefühle": {
    icon: "💭",
    words: [
      { ar: "سَعيد", en: "happy", tr: "sa'id" },
      { ar: "حَزين", en: "sad", tr: "hazin" },
      { ar: "تَعْبان", en: "tired", tr: "ta'ban" },
      { ar: "نَعْسان", en: "sleepy", tr: "na'san" },
      { ar: "جَوْعان", en: "hungry (m)", tr: "jaw'an" },
      { ar: "جَوْعانة", en: "hungry (f)", tr: "jaw'ana" },
      { ar: "مُتَحَمِّس", en: "excited", tr: "mutahammis" },
      { ar: "جاهِز", en: "ready", tr: "jahiz" },
    ],
  },
  "Pronomen & Fragewörter": {
    icon: "❓",
    words: [
      { ar: "أَنا", en: "I", tr: "ana" },
      { ar: "أَنْتَ", en: "you (m)", tr: "anta" },
      { ar: "أَنْتِ", en: "you (f)", tr: "anti" },
      { ar: "أَنْتُم", en: "you all", tr: "antum" },
      { ar: "هُوَّ", en: "he", tr: "huwa" },
      { ar: "هِيَّ", en: "she", tr: "hiya" },
      { ar: "هُم", en: "they", tr: "hum" },
      { ar: "نَحْنُ", en: "we", tr: "nahnu" },
      { ar: "ما", en: "what, not", tr: "ma" },
      { ar: "ماذا", en: "what", tr: "maza" },
      { ar: "مَن", en: "who", tr: "man" },
      { ar: "أَيْن", en: "where", tr: "ayna" },
      { ar: "مَتى", en: "when", tr: "mata" },
      { ar: "كَيْف", en: "how", tr: "kayf" },
      { ar: "لِماذا", en: "why", tr: "limaza" },
      { ar: "أَيّ", en: "which, any", tr: "ayy" },
      { ar: "أَيّة", en: "which (f)", tr: "ayya" },
      { ar: "هَل", en: "is, do, does", tr: "hal" },
      { ar: "هٰذا", en: "this (m)", tr: "haza" },
      { ar: "هٰذِهِ", en: "this (f)", tr: "hazihi" },
      { ar: "ذٰلِك", en: "that", tr: "zalika" },
    ],
  },
  "Besitz & Haben": {
    icon: "🔑",
    words: [
      { ar: "عِنْدي", en: "I have", tr: "'indi" },
      { ar: "عِنْدَك", en: "you have (m)", tr: "'indak" },
      { ar: "عِنْدِك", en: "you have (f)", tr: "'indik" },
      { ar: "عِنْدهُ", en: "he has", tr: "'indahu" },
      { ar: "عِنْدها", en: "she has", tr: "'indaha" },
      { ar: "عِنْدنا", en: "we have", tr: "'indana" },
      { ar: "عِنْدكُم", en: "you all have", tr: "'indakum" },
      { ar: "عِنْدهُم", en: "they have", tr: "'indahum" },
      { ar: "عِنْد", en: "have, has, at", tr: "'ind" },
      { ar: "لَيْسَ عِنْدي", en: "I do not have", tr: "laysa 'indi" },
      { ar: "لَيْسَ عِنْدَك", en: "you do not have (m)", tr: "laysa 'indak" },
      { ar: "لَيْسَ عِنْدِك", en: "you do not have (f)", tr: "laysa 'indik" },
      { ar: "لَيْسَ عِنْدهُ", en: "he does not have", tr: "laysa 'indahu" },
      { ar: "لَيْسَ عِنْدها", en: "she does not have", tr: "laysa 'indaha" },
      { ar: "مَعي", en: "with me", tr: "ma'i" },
      { ar: "مَعِك", en: "with you", tr: "ma'ik" },
      { ar: "مَعَهُ", en: "with him", tr: "ma'ahu" },
      { ar: "مَعَها", en: "with her", tr: "ma'aha" },
      { ar: "مَعَ", en: "with", tr: "ma'a" },
    ],
  },
  "Präpositionen & Orte": {
    icon: "📍",
    words: [
      { ar: "في", en: "in, at", tr: "fi" },
      { ar: "عَلى", en: "on, over", tr: "'ala" },
      { ar: "إِلى", en: "to, at", tr: "ila" },
      { ar: "مِن", en: "from, of", tr: "min" },
      { ar: "عَن", en: "about, for", tr: "'an" },
      { ar: "أَمام", en: "in front of", tr: "amam" },
      { ar: "أَمامي", en: "in front of me", tr: "amami" },
      { ar: "أَمامَك", en: "in front of you", tr: "amamak" },
      { ar: "خَلْف", en: "behind", tr: "khalf" },
      { ar: "خَلْفي", en: "behind me", tr: "khalfi" },
      { ar: "خَلْفَك", en: "behind you", tr: "khalfak" },
      { ar: "بِجانِب", en: "next to", tr: "bijanib" },
      { ar: "تَحْت", en: "under", tr: "taht" },
      { ar: "قَريب مِن", en: "close to", tr: "qarib min" },
      { ar: "بَعيد", en: "far", tr: "ba'id" },
      { ar: "هُنا", en: "here", tr: "huna" },
      { ar: "هُناك", en: "there", tr: "hunak" },
      { ar: "ها", en: "there", tr: "ha" },
    ],
  },
  "Konjunktionen & Adverbien": {
    icon: "🔗",
    words: [
      { ar: "وَ", en: "and", tr: "wa" },
      { ar: "و", en: "and", tr: "wa" },
      { ar: "أَو", en: "or", tr: "aw" },
      { ar: "لٰكِنّ", en: "but", tr: "lakin" },
      { ar: "أَنْ", en: "that, to", tr: "an" },
      { ar: "إذا", en: "if", tr: "iza" },
      { ar: "لِأَنَّ", en: "because", tr: "li'anna" },
      { ar: "لِأَنَّني", en: "because I", tr: "li'annani" },
      { ar: "لِأَنَّهُ", en: "because he", tr: "li'annahu" },
      { ar: "لِأَنَّها", en: "because she", tr: "li'annaha" },
      { ar: "لِأَنَّك", en: "because you (m)", tr: "li'annak" },
      { ar: "لِأَنِّك", en: "because you (f)", tr: "li'annik" },
      { ar: "بِسَبَب", en: "because of", tr: "bisabab" },
      { ar: "لَنْ", en: "will not", tr: "lan" },
      { ar: "كَثيراً", en: "a lot, very much", tr: "kathiran" },
      { ar: "كَثير", en: "a lot of, many", tr: "kathir" },
      { ar: "أَكْثَر", en: "more", tr: "akthar" },
      { ar: "جِدّاً", en: "very", tr: "jiddan" },
      { ar: "أَيْضاً", en: "also, too", tr: "aydan" },
      { ar: "فَقَط", en: "only", tr: "faqat" },
      { ar: "كُلّ", en: "all, each", tr: "kull" },
      { ar: "كُلّ شَيْء", en: "everything", tr: "kull shay'" },
      { ar: "نَفْس", en: "same", tr: "nafs" },
      { ar: "أُخْرى", en: "other, another (f)", tr: "ukhra" },
      { ar: "آخَر", en: "other, another", tr: "akhar" },
      { ar: "مَعاً", en: "together", tr: "ma'an" },
      { ar: "بِٱلْضَّبْط", en: "exactly", tr: "bid-dabt" },
      { ar: "طَبْعاً", en: "of course", tr: "tab'an" },
      { ar: "تَماماً", en: "absolutely, totally", tr: "tamaman" },
      { ar: "صَحيح", en: "true, correct", tr: "sahih" },
      { ar: "غَلَط", en: "wrong", tr: "ghalat" },
      { ar: "بِسُرْعة", en: "quickly", tr: "bisur'a" },
      { ar: "نَعَم", en: "yes", tr: "na'am" },
      { ar: "لا", en: "no", tr: "la" },
      { ar: "بِلا", en: "without", tr: "bila" },
      { ar: "لا أَحَد", en: "no one", tr: "la ahad" },
      { ar: "أَبَداً", en: "at all, never", tr: "abadan" },
      { ar: "لِلْأَسَف", en: "unfortunately", tr: "lil-asaf" },
      { ar: "مِن اَلْمُمْكِن أَنْ", en: "can", tr: "min al-mumkin an" },
      { ar: "كافي", en: "enough", tr: "kafi" },
      { ar: "كاف", en: "enough", tr: "kaf" },
    ],
  },
  Alltagsgegenstände: {
    icon: "🎒",
    words: [
      { ar: "هاتِف", en: "phone", tr: "hatif" },
      { ar: "حاسوب", en: "computer", tr: "hasub" },
      { ar: "لاب توب", en: "laptop", tr: "lab tub" },
      { ar: "قَلَم", en: "pen, pencil", tr: "qalam" },
      { ar: "قَلَم رَصاص", en: "pencil", tr: "qalam rasas" },
      { ar: "دَفْتَر", en: "notebook", tr: "daftar" },
      { ar: "شَنْطة", en: "bag", tr: "shanta" },
      { ar: "مَحْفَظة", en: "wallet", tr: "mahfaza" },
      { ar: "مِفْتاح", en: "key", tr: "miftah" },
      { ar: "عِلْكة", en: "chewing gum", tr: "'ilka" },
      { ar: "سي دي", en: "CD", tr: "si di" },
      { ar: "كوب", en: "cup, mug", tr: "kub" },
      { ar: "تاج", en: "crown", tr: "taj" },
    ],
  },
  "Hobbys & Aktivitäten": {
    icon: "🎮",
    words: [
      { ar: "نَشاط", en: "activity", tr: "nashat" },
      { ar: "أَنْشِطة", en: "activities", tr: "anshita" },
      { ar: "فِكْرة", en: "idea", tr: "fikra" },
      { ar: "موسيقى", en: "music", tr: "musiqa" },
      { ar: "فيلْم", en: "film", tr: "film" },
      { ar: "فَنّ", en: "art", tr: "fann" },
      { ar: "كُرة اَلْقَدَم", en: "soccer", tr: "kurat al-qadam" },
      { ar: "لَعْب", en: "playing", tr: "la'b" },
      { ar: "اَلْجَري", en: "running", tr: "al-jary" },
      { ar: "اَلْسِّباحة", en: "swimming", tr: "as-sibaha" },
      { ar: "اَلْكِتابة", en: "writing", tr: "al-kitaba" },
      { ar: "اَلْقِراءة", en: "reading", tr: "al-qira'a" },
      { ar: "اَلْنَّوْم", en: "sleeping", tr: "an-nawm" },
      { ar: "اَلْتَّصْوير", en: "photography", tr: "at-taswir" },
      { ar: "مُشاهَدة", en: "watching", tr: "mushahada" },
      { ar: "عالَم", en: "world", tr: "'alam" },
      { ar: "حَياة", en: "life", tr: "hayat" },
      { ar: "مُسْتَقْبَل", en: "future", tr: "mustaqbal" },
      { ar: "أَخْبار", en: "news", tr: "akhbar" },
    ],
  },
  Namen: {
    icon: "👤",
    words: [
      { ar: "مُحَمَّد", en: "Mohamed", tr: "muhammad" },
      { ar: "عُمَر", en: "Omar", tr: "'umar" },
      { ar: "إِبْراهيم", en: "Ibrahim", tr: "ibrahim" },
      { ar: "مَحْمود", en: "Mahmoud", tr: "mahmud" },
      { ar: "غَسّان", en: "Ghassan", tr: "ghassan" },
      { ar: "تامِر", en: "Tamer", tr: "tamir" },
      { ar: "فَريد", en: "Farid", tr: "farid" },
      { ar: "بَشير", en: "Bashir", tr: "bashir" },
      { ar: "عَلي", en: "Ali", tr: "'ali" },
      { ar: "زَيد", en: "Zayd", tr: "zayd" },
      { ar: "دَوود", en: "David", tr: "dawud" },
      { ar: "شادي", en: "Shadi", tr: "shadi" },
      { ar: "رَواد", en: "Rawad", tr: "rawad" },
      { ar: "سيث", en: "Seth", tr: "sith" },
      { ar: "مايْك", en: "Mike", tr: "mayk" },
      { ar: "جورج", en: "George", tr: "jurj" },
      { ar: "بوب", en: "Bob", tr: "bob" },
      { ar: "سام", en: "Sam", tr: "sam" },
      { ar: "جودي", en: "Judy", tr: "judi" },
      { ar: "روزا", en: "Rosa", tr: "ruza" },
      { ar: "ريم", en: "Reem", tr: "rim" },
      { ar: "رانْيا", en: "Rania", tr: "ranya" },
      { ar: "سامْية", en: "Samia", tr: "samya" },
      { ar: "مُنيرة", en: "Mounira", tr: "munira" },
      { ar: "أَرْوى", en: "Arwa", tr: "arwa" },
      { ar: "لَمى", en: "Lama", tr: "lama" },
      { ar: "زَيْنة", en: "Zeina", tr: "zayna" },
      { ar: "لَيْلى", en: "Laila", tr: "layla" },
      { ar: "مَها", en: "Maha", tr: "maha" },
      { ar: "جو", en: "Joe", tr: "ju" },
      { ar: "كَري", en: "Carrie", tr: "kari" },
      { ar: "دُوو", en: "Duo", tr: "duo" },
    ],
  },
  Sonstige: {
    icon: "📝",
    words: [
      { ar: "اِسْم", en: "name", tr: "ism" },
      { ar: "اِسْمي", en: "my name", tr: "ismi" },
      { ar: "اِسْمَك", en: "your name (m)", tr: "ismak" },
      { ar: "اِسْمِك", en: "your name (f)", tr: "ismik" },
      { ar: "اِسْمهُ", en: "his name", tr: "ismuhu" },
      { ar: "اِسْمها", en: "her name", tr: "ismuha" },
      { ar: "شَيْء", en: "thing, anything", tr: "shay'" },
      { ar: "مِثْل", en: "like", tr: "mithl" },
      { ar: "يا", en: "hey, oh", tr: "ya" },
      { ar: "ذو", en: "with, of", tr: "zu" },
      { ar: "أول", en: "first", tr: "awwal" },
      { ar: "جُدَد", en: "new (pl)", tr: "judad" },
      { ar: "بُيوت", en: "houses", tr: "buyut" },
      { ar: "شَباب", en: "guys", tr: "shabab" },
      { ar: "سادة", en: "gentlemen", tr: "sada" },
      { ar: "مَلِكة", en: "queen", tr: "malika" },
      { ar: "ضَواحي", en: "the suburbs", tr: "dawahi" },
      { ar: "اَلْأَزْهَر", en: "Al-Azhar", tr: "al-azhar" },
      { ar: "هارْفارْد", en: "Harvard", tr: "harvard" },
      { ar: "سيرة", en: "biography", tr: "sira" },
      { ar: "شاشة", en: "screen, display", tr: "shasha" },
      { ar: "طوب", en: "brick", tr: "tub" },
      { ar: "مو", en: "mu", tr: "mu" },
      { ar: "سوء", en: "bad", tr: "su'" },
      { ar: "جاك", en: "jack", tr: "jak" },
      { ar: "دور", en: "role, floor, turn", tr: "dawr" },
      { ar: "رود", en: "rhode", tr: "rud" },
      { ar: "ري", en: "watering", tr: "ri" },
      { ar: "زار", en: "visited", tr: "zar" },
      { ar: "زي", en: "uniform, costume", tr: "zayy" },
      { ar: "واي", en: "wi", tr: "way" },
      { ar: "سي", en: "c", tr: "si" },
      { ar: "رَ", en: "See", tr: "ra" },
      { ar: "توب", en: "laptop", tr: "tub" },
      { ar: "طيب", en: "kind", tr: "tayyib" },
    ],
  },
};
